### ISSUE TITLE
Digest iterations infinite loop in HTML5 mode

### ISSUE THREAD

**Issue by ruddles** [AzureAD/azure-activedirectory-library-for-js#42] opened 2014-11-18 15:37 UTC
If I add the library to a project that uses html5mode and enter a URL with a # on the end (e.g. http://localhost:9000# or http://localhost:9000/# ) the developer console is battered with errors:

```
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
```

If I turn off html5mode or remove the `adalAuthenticationServiceProvider.init` call in app.js then everything is fine.  I've had a quick look through but I cannot see what's causing it.  I've added a sample at https://github.com/ruddles/ADALIssue which you can clone, npm install && bower install, grunt serve and then test the app by opening the developer console, and add a # to the end of the URL.

I've tested this in both chrome and firefox on a mac.

**Comment by omercs** [comment] 2015-01-08 22:59
I will close this. If you repro after following the suggestions, please open again.

**Comment by brphelps** [comment] 2015-04-06 23:13
Any chance this issue could be revisited? It looks like there are some strong assumptions about how routing is done to fix, it would be nicer to just have a real fix that didn't involve ng-route specific stuff.

**Comment by gkiely** [comment] 2015-05-15 02:51
@omercs I've experienced this same issue.

**Comment by bpatra** [comment] 2015-05-22 00:08
@omercs same issue for me, thus the '.otherwise' workaround worked. Thanks.

**Comment by drGarbinsky** [comment] 2015-07-06 23:01
I am still experiencing a similar issue. Any guidance on how to resolve this would be very helpful.

http://stackoverflow.com/questions/30768562/app-is-re-initializing-the-first-time-adal-protected-url-is-accessed-via-http

**Comment by shekhardesigner** [comment] 2015-10-04 20:18
I too tried with the default route way, didn't work. Anyway I am not using HTML5 mode yet I have this issue. As soon as office returns after loggin in - I see this error.

Strange thing is, when I reload (F5), this issue goes away. 

![image](https://cloud.githubusercontent.com/assets/3298585/10270011/1594754a-6b03-11e5-986c-df906cad1284.png)

**Comment by barisbikmaz** [comment] 2015-10-28 09:48
The problem still exists in html5Mode when adal tries to get the tokens for the first time. All methods in my constructors are excuted 10 times because of the infinite digest loop. You can reproduce the issue if you clear all adal stuff from localStorage and load the page

 `$routeProvider
                    .when('/',
                    {
                        templateUrl: 'main/main.html',
                        requireADLogin: true
                    })
                    .otherwise(
                    {
                        redirectTo: '/'
                    });`

**Comment by martellaj** [comment] 2015-11-09 18:38
Y'all should open this issue back up for awareness, given that it's a work item for someone now.

**Comment by venkateshappala** [comment] 2016-01-22 19:38
Any fix is available for this?

**Comment by martellaj** [comment] 2016-03-04 23:31
@venkateshappala Don't rely on it... look at when this issue was opened.

**Comment by mrjono1** [comment] 2016-03-14 22:59
I experienced this issue as well, changing from http to https seems to have stopped the redirect loop

**Comment by PavelPikat** [comment] 2016-03-15 08:55
We did something like this to address the issue:

$rootScope.$on('$locationChangeStart', function (e) {
                if ($location.path().indexOf('access_token') > -1 ||
                    $location.path().indexOf('id_token') > -1) {
                    e.preventDefault();
                }
            });

We've also added similar checks for id_token and access_token in our $urlRouterProvider.otherwise function

**Comment by nigel-dewar** [comment] 2016-03-30 23:38
I am having this issue too. Cannot solve it. Tried LOTS of different things. I am using ui-router.

cheers

**Comment by gabbsmo** [comment] 2016-03-31 12:05
Was this solved with this PR? It is currently merged to dev. https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/138/commits/60b6639f9fcd6c5bba483b0c082900f26f860b80

**Comment by tushargupta51** [comment] 2016-04-01 00:55
@gabbsmo not yet. That PR was for a different issue.

**Comment by nigel-dewar** [comment] 2016-04-01 23:17
Thought I should mention, I am using adal version 1.7 and not the latest 1.8.

The reason I have to use 1.7 is because of the issue with 1.8 where when you return a user back to the application, the routes break.

So I might be stuck between 2 buggy versions, 1.7 perhaps has the infinite loop issues, and 1.8 has the returned routing issue.

When you guys say PR, what do you mean? Do you mean Pre Release? version

**Comment by tushargupta51** [comment] 2016-04-01 23:21
PR == Pull Request

**Comment by nigel-dewar** [comment] 2016-04-01 23:34
Lol ok Thanks @tushargupta51

**Comment by jonfreberg** [comment] 2016-04-28 14:29
Any news on this one?

**Comment by tushargupta51** [comment] 2016-04-28 17:02
@jonfreberg Can you please a share a repro or console logs? You can turn on logging by adding this to app.js:

Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    }
};

**Comment by jonfreberg** [comment] 2016-04-29 07:20
I added logging. Will revert with more info when the endless loop kicks back in.

**Comment by jonfreberg** [comment] 2016-04-29 08:16
![endless-loop-with-logging](https://cloud.githubusercontent.com/assets/631627/14911100/5d894e96-0df3-11e6-87be-084e44e59636.PNG)

**Comment by jonfreberg** [comment] 2016-04-29 08:17
![endless-session-storage](https://cloud.githubusercontent.com/assets/631627/14911118/8604029e-0df3-11e6-9762-557f82181f7b.PNG)

**Comment by jonfreberg** [comment] 2016-04-29 08:17
I cant see anything about the wrong nonce in the logging.

**Comment by tushargupta51** [comment] 2016-04-29 17:27
@jonfreberg Can you also provide value of user.profile.nonce (you will need to debug to get to this value) along with the values in the storage (pic posted above)? Are you setting an .otherwise route in your config? I have seen these loops because of that too. Sharing your config will help debug further. Thanks!

**Comment by jonfreberg** [comment] 2016-05-02 06:19
Values from before the endless loop starts:

userInfo.profile.nonce: 2cce876e-fc24-4afc-9acf-0b5fa2cda89b
adal.nonce.idtoken:     2cce876e-fc24-4afc-9acf-0b5fa2cda89b

I will provide those two after the loop starts as well. So thats the two nonce's adal checks that are equal?  And if not, the adal.login.error gets set in the session storage?

No, I'm not using an .otherwise route for now, just to exclude that. This is my setup:

$stateProvider
            .state("private", {
                abstract: true,
                template: "<ui-view/>"
            }).state("private.utility", {
                url: "/utility",
                templateUrl: "app/views/utility.html",
                requireADLogin: true
            });

**Comment by jonfreberg** [comment] 2016-05-02 07:24
Because of the endless loop, the developer tools refreshes so I cant get too the userinfo object to see the nonce value.

**Comment by gabbsmo** [comment] 2016-05-02 14:09
@jonfreberg You can check "preserve log" in the Chrome console and console.log(userinfo) from your code.

**Comment by talismax** [comment] 2016-05-03 16:04
I have the same issue. I have basically the simplest possible Angular/ADAL app with no routing:

```
'use strict';
angular.module('app', ['AdalAngular', 'wj'])
.config(['$httpProvider', 'adalAuthenticationServiceProvider', function ($httpProvider, adalProvider) {

    var endpoints = {
        "https://localhost:44347": "https://something.com/myapi"
    }
    adalProvider.init({
        instance: 'https://login.microsoftonline.com/',
        tenant: 'something.onmicrosoft.com',
        clientId: '[my client id],
        endpoints: endpoints
    }, $httpProvider);
}]);

'use strict';
angular.module('app')
.controller('appCtrl', ['$scope', '$http', 'adalAuthenticationService', function ($scope, $http, adalService ) {

    $scope.login = function () {
        adalService.login(); 
    }

    $scope.logout = function () {
        adalService.logOut(); 
    }
}]);
```
As soon as I login I get the errors:
![image](https://cloud.githubusercontent.com/assets/2261681/14989692/ab900534-111e-11e6-9ba0-e3e50894638f.png)

**Comment by adamauckland** [comment] 2016-05-04 16:20
Jumping in because I've managed to solve the "Nonce is not the same as" problem with a workaround:

Looking in the DOM inspector, I can see that there are multiple ADAL renew token iframes nested. I believe what is happening is that the iFrame is renewing the token and ending up back at `index.html` therefore starting a new version of the app. 

This new app then periodically tries to renew the token out of sync with the parent. Because they share the same context the GUIDS are overwriting in sessionstorage.

I have worked around this problem by detecting if the app is inside an iframe as part of the bootstrap process, then ONLY starting up angular-adal and not loading any of my other app modules. It seems to solve the infinite looping problem.


HOWEVER: this does not solve the infdig issue on a brand new instance of the app which happens consistently unless I comment out `$window.location.hash = '';` on line 88 of adal-angular.js

                      ```
  if ($location.$$html5) {
                            $window.location = $window.location.origin + $window.location.pathname;
                        } else {
                            //$window.location.hash = '';
                        }
```

**Comment by jonfreberg** [comment] 2016-05-09 11:41
Thanks for the reply @adamauckland ! 

Could you give a little more details on how you only start up angular-adal if the app is inside an iFrame in the bootstrap process?

**Comment by adamauckland** [comment] 2016-05-09 14:51
Yep, @jonfreberg. It's really not anything clever. Conceptually, we just create the primary module differently depending on if we're the top frame or not like this:

```
if (window.self === window.top) {
    angular.module('app', [
        // the full list of all modules goes here
    ]);
} else {
    angular.module('app', [
         'AdalAngular',
    ]);
}

```

Obviously the actual implementation has a bit more checking around it, but that's the principle.

**Comment by jonfreberg** [comment] 2016-05-10 09:20
Thanks @adamauckland . I'll give it a go. 
What version of angular, adal and adal-angular are you using?

**Comment by adamauckland** [comment] 2016-05-10 09:46
@jonfreberg 

Angular 1.4.7
AdalJS v1.0.10
adal-angular v1.0.10

**Comment by fairmutex** [comment] 2016-06-06 14:17
Can someone put an example together that works? Since I am having big trouble with this issue

**Comment by tushargupta51** [comment] 2016-06-09 20:39
We have Pull Requests submitted that will address the issues mentioned here:
1. App reloading on token renewal. Please see #151 for more details.
2. Digest iterations: This issue can be caused due to multiple reasons in an angular app. One of the main reasons, adal users were hitting this was the update to location.hash using $window.location. I have updated that to use $location.hash for both html5 and non-html5 modes. That should fix the locationChangeStart digest iterations.

These PRs will be merged soon. I will the close the issue then. If you still run into this issue, let us know, we can re-visit this.

**Comment by fairmutex** [comment] 2016-06-24 08:40
I have tried all the work arounds suggested here and nothing is working. Can someone put together a sample app that works? It will help me and new comers to the problem as well.

**Comment by jjalfaro** [comment] 2016-07-11 22:29
Hi, I'm also having same issues here I already try all the possible sugestions that I found and nothing works. Someone was able to male this work fine, that can give me some hints to see if I can make it work.

thanks!

**Comment by tushargupta51** [comment] 2016-07-13 16:31
@jjalfaro have you tried this: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q2-my-app-gets-into-an-infinite-loop-sometimes-leading-to-digest-iterations-error

**Comment by jjalfaro** [comment] 2016-07-13 22:47
Yes I try it out it is giving me the same error, this is if I run it on IE
11, if I run it on Chrome it blocks completely the browser

[image: Inline image 1]

**Comment by tushargupta51** [comment] 2016-07-20 19:58
We have released 1.0.11 with fixes to some of the digest iterations issue. Please use 1.0.11 and have a look here if you are still running into this issue: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q2-my-app-gets-into-an-infinite-loop-sometimes-leading-to-digest-iterations-error

@jjalfaro I am closing this issue for now but feel free to open a new issue with the details: logs, traces if you still experience the loop with the new release.

**Closed by tushargupta51** 2016-07-20 19:58 UTC
Labels: Area: Digest Iterations, bug, P1, PR Submitted

**Comment by dgodwin1175** [comment] 2017-04-07 07:16
I was facing this digest iterations issue with version 1.0.0.
I worked around it by setting the  $window.location.hash = '' as already mentioned, however this meant that my token would only renew on route changes, but I need it to renew as required.
So I decided to update to the latest version (1.0.14), but now, I'm in a different kind of infinite loop.
When launching my app, Chrome locks up and then runs out of memory.  Has anyone seen this before?  All I've done is swap out the two js files!

**Comment by nigel-dewar** [comment] 2017-04-07 07:53
Yes i have. Especially if using ui-router. A r e u using ui router?


Sent from Samsung Mobile


-------- Original message --------
From: dgodwin1175
Date:07/04/2017 17:16 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Comment
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] Digest iterations infinite loop in HTML5 mode (#42)


I was facing this digest iterations issue with version 1.0.0.
I worked around it by setting the $window.location.hash = '' as already mentioned, however this meant that my token would only renew on route changes, but I need it to renew as required.
So I decided to update to the latest version (1.0.14), but now, I'm in a different kind of infinite loop.
When launching my app, Chrome locks up and then runs out of memory. Has anyone seen this before? All I've done is swap out the two js files!

**Comment by dgodwin1175** [comment] 2017-04-07 08:11
Yes I certainly am, and I'd really prefer not to have to rip it out.  Have you managed to resolve or at least find the root cause?

**Comment by nigel-dewar** [comment] 2017-04-07 08:42
Yes i have. The issue is well documented if u do a search for adal.js and ui-router.

There are a few things that need to be done, to prevent its crazy looping.

Its friday 6.40pm and i need to cook dinner (my wife is waiting), if you cant get it sorted via some searching, then i can post the code and explanation in like 1 hour from now. Sorry to keep u hanging.


Sent from Samsung Mobile


-------- Original message --------
From: dgodwin1175
Date:07/04/2017 18:11 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Comment
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] Digest iterations infinite loop in HTML5 mode (#42)


Yes I certainly am, and I'd really prefer not to have to rip it out. Have you managed to resolve or at least find the root cause?

**Comment by dgodwin1175** [comment] 2017-04-07 08:45
Pls post when you can.  No need to do it on your Friday night!  Thanks so much.

**Comment by nigel-dewar** [comment] 2017-04-07 09:16
Ok mate, managed to fire up laptop inbetween dinner.

Here is what you need to do

In your Angular run block you need to do this.

    $rootScope.$state = $state;
    var isAdalFrame = window !== window.parent;
        $rootScope.$on('$locationChangeStart', function (e) {
            if ($location.path().indexOf('access_token') > -1 ||
                $location.path().indexOf('id_token') > -1 ||
                $location.path().indexOf('/error=') === 0 ||
                isAdalFrame
            ) {
                e.preventDefault();
            }
        });

so if your angular run might look like this

angular.module('app').run('runBlock');

function runBlock($rootScope, $location, $state) {
     $rootScope.$state = $state;
    var isAdalFrame = window !== window.parent;
        $rootScope.$on('$locationChangeStart', function (e) {
            if ($location.path().indexOf('access_token') > -1 ||
                $location.path().indexOf('id_token') > -1 ||
                $location.path().indexOf('/error=') === 0 ||
                isAdalFrame
            ) {
                e.preventDefault();
            }
        });
}

Secondly you will need to do this

In your route code, (most likely in your routeConfig class), instead of doing this $urlRouterProvider.otherwise('/');

You will need to do this

$urlRouterProvider.otherwise(
               function ($injector, $stateParams) {
                   var isAdalFrame = window !== window.parent;
                   var $state = $injector.get('$state'),
                       $$path = $stateParams.$$path,
                       $$url = $stateParams.$$url,
                       $log = $injector.get('$log');

                   if ($$path) {
                       if (($$path.indexOf('id_token') !== -1 &&
                           $$url.indexOf('id_token') !== -1) ||
                           ($$path.indexOf('access_token') !== -1 &&
                           $$url.indexOf('access_token') !== -1) ||
                           $$path.indexOf('/error=') !== -1) {
                           // Do nothing if we have adal's token in the url
                       } else if (!isAdalFrame) {
                           $state.go('home');
                       }
                   }
                   else if (!isAdalFrame) {
                       $state.go('home');
                   }
               });

Make your default route 'home' or something like that.

What is happening, is ui-router does not play nice with adal.js.  I have found no version of adal.js does.
Without these changes, things get thrown into a nasty loop like you have found.
I did spend some time trying to identify exactly what it was, but in the end I found the code just work and so I settled with it.

Give it a shot and let me know how you go! Hope it works for you mate. I have found it works ok.

**Comment by dgodwin1175** [comment] 2017-04-10 09:22
It doesn't appear to work, the browser hangs on this piece of code from angular.js, before my .otherwise() function is called:
    injector.invoke(['$rootScope', '$rootElement', '$compile', '$injector',
       function bootstrapApply(scope, element, compile, injector) {
        scope.$apply(function() {
          element.data('$injector', injector);
          compile(element)(scope);
        });
      }]
    );
    return injector;
  };

**Comment by nigel-dewar** [comment] 2017-04-10 10:13
Hmmm. I will post a sample repo for u to try. Ul just need to swap out clientid etc foe urs.

What version of angular u using.?
Also what version of ui router?

And..... what version of adal.js?

This will help me with sample.


Sent from Samsung Mobile


-------- Original message --------
From: dgodwin1175
Date:10/04/2017 19:22 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Comment
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] Digest iterations infinite loop in HTML5 mode (#42)


It doesn't appear to work, the browser hangs on this piece of code from angular.js, before my .otherwise() function is called:
injector.invoke(['$rootScope', '$rootElement', '$compile', '$injector',
function bootstrapApply(scope, element, compile, injector) {
scope.$apply(function() {
element.data('$injector', injector);
compile(element)(scope);
});
}]
);
return injector;
};

**Comment by dgodwin1175** [comment] 2017-04-10 14:52
I'm using angular 1.5.8
ui-router 2.18
adal.js/adal-angular 1.0.14

**Comment by nigel-dewar** [comment] 2017-04-10 21:37
Cheers. Ill post sample this morn.


Sent from Samsung Mobile


-------- Original message --------
From: dgodwin1175
Date:11/04/2017 00:52 (GMT+10:00)
To: AzureAD/azure-activedirectory-library-for-js
Cc: nigel-dewar , Comment
Subject: Re: [AzureAD/azure-activedirectory-library-for-js] Digest iterations infinite loop in HTML5 mode (#42)


I'm using angular 1.5.8
ui-router 2.18
adal.js/adal-angular 1.0.14
