### ISSUE TITLE
adal js automatically redirecting the user to login page silent token refreshing is not happening with the cacheLocation as localStorage

### ISSUE THREAD

**Issue by aryanreddy** [AzureAD/azure-activedirectory-library-for-js#625] opened 2017-09-14 15:35 UTC
Configuration for adal js in single page application:

adalAuthenticationServiceProvider.init(
                {
                    tenant: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    clientId: clientId,
                    cacheLocation: 'localStorage',
                    endpoints: endpoints,
               }, $httpProvider);
2. if cachceLocation is sessionStorage then application is in continuous loop in edge browser.

please suggest us with the best approach. because if user is doing some operation with the system and redirected to login page then they will see some discrepancy. 

This is one of the blockage issue for us. please provide us with the fix.

**Comment by rohitnarula7176** [comment] 2017-09-15 23:31
@aryanreddy The redirection to login page after receiving the token in the redirect response is by design. There is a known issue with the Edge browser where session storage values are lost after redirection which forces the library into an infinite loop. Do you see values like "invalid_state" saved in the storage when you encounter this issue. We are tracking this issue with the Edge team. Can you share your code to help us understand if this is the same issue?

**Comment by rohitnarula7176** [comment] 2017-10-21 16:28
@aryanreddy Closing this issue due to lack of information. Please reopen if it is not resolved for you.

**Closed by rohitnarula7176** 2017-10-21 16:28 UTC
