### ISSUE TITLE
What about an option to automatically renew the token before it expires?

### ISSUE THREAD

**Issue by linsolas** [AzureAD/azure-activedirectory-library-for-js#215] opened 2016-01-11 08:32 UTC
Hello,

We are using ADAL.js for some internal websites.
As per my understanding, the library is checking the validity of the token before every request made to the server. When the token is expired or about to expire (less than 2 minutes), the token is requested again and renewed.
I was wondering if it would not be a good idea to automatically request a token renewal **before** it expires.
In our specific context, the token has a really short TTL (about 10 minutes). So we can imagine to have some sort of timer on the library that will be run every 8 or 9 minutes (of course this time will be dependent on the TTL and the `config.expireOffsetSeconds || 120 seconds`) to renew the token. This way, the token should never expires until the user is logged on the application.

What do you think? Don't you think it could be useful to have - optionally - a timer on the library that renew the token automatically?

(we use ADALjs 1.0.0 with Angular)

**Comment by weijjia** [comment] 2016-01-14 19:20
I think this should be something handled at the app level. As a library, we provide the functionality to renew the token, and the app could have such a timer to make sure the token never expired once user logged in.

**Comment by tushargupta51** [comment] 2016-03-07 20:16
Until the time a user is logged in and there is a valid session cookie present, ADAL will renew the expired token or about to expire tokens. From a user perspective, this renewal is happening in the backend and it should appear to them that the token never really expired as long as a valid session with AAD exists. I don't think there is much difference in renewing the token before it expires or after as long as there is a token available that can be served up to the protected API.
Closing this issue. Please feel free to reopen if you have any comments.

**Closed by tushargupta51** 2016-03-07 20:16 UTC

**Comment by ruisilva450** [comment] 2016-05-24 11:25
Can you explain how can the library renew the token? I'm getting 401 errors after some time.
And how can I renew the token programmatically?

**Comment by tushargupta51** [comment] 2016-05-24 22:49
@ruisilva450 When user logs in, AAD sets a cookie. As long as that cookie is valid, ADAL can renew token silently whenever its needed. Programmatically, you can call `aquireToken` api to renew the token.

**Comment by ruisilva450** [comment] 2016-05-25 11:04
@tushargupta51 I'm getting another error when I try to execute `acquireToken` I get the following promise response, maybe by another reason but here it goes:
```AADSTS70005: response_type 'token' is not enabled for the application```

**Comment by tushargupta51** [comment] 2016-05-25 17:27
@ruisilva450 That sounds like a configuration issue. Do you have `oauth2AllowImplicitFlow` set to true in manifest. This might help: http://stackoverflow.com/questions/29326918/adal-js-response-type-token-is-not-supported

**Comment by ruisilva450** [comment] 2016-05-25 19:50
@tushargupta51 you're right. It fixed my problem. Thanks!
Maybe this is what was causing the library to not renew the token automatically?

**Comment by tushargupta51** [comment] 2016-05-25 20:45
@ruisilva450 Glad it worked for you! Maybe token renewal was not working because of this as AAD was rejecting the request with `response_type = token`.

**Comment by katagaStyle** [comment] 2016-05-27 09:43
We have some token expire issues. When local storage is empty then everything works fine. After some time we get in trouble when we reuse the application. We can reproduce this behaviour when setting expire token in local storage to expired (e.g. 0). This causes that broken interceptor is thrown and we end up in an endloss refresh loop. Same behavior in release1.0.11 branch. :(

**Comment by aryanreddy** [comment] 2017-09-14 18:41
hi tushargupta,
i am adding my application configuration below for your reference, but the silent token renewal is not happening. when ever the token expires it automatically redirecting the user to supply the credentials again. i am not able figure it out what is the issue and when the token will expires.

**Configuration for single page application:**

          var endpoints = {};
            endpoints[webApiUrl] = clientId;

            adalAuthenticationServiceProvider.init(
                {
                    tenant: 'microsoft.onmicrosoft.com',
                    clientId: clientId,
                    cacheLocation: 'localStorage',
                    endpoints: endpoints,
                    anonymousEndpoints:["App/header.html","App/Footer/footer.html"]
                }, $httpProvider);

We are getting Token renewal operation failed exception even though we are some actions on the page.

Can you please help me to fix this issue, this is one of the major blocking issue for us.
