### ISSUE TITLE
Problem with _renewIdToken. Token is never renewed after the expireOffsetSeconds

### ISSUE THREAD

**Issue by rtarasov** [AzureAD/azure-activedirectory-library-for-js#723] opened 2018-02-28 12:43 UTC
Hi Guys!
It seems like _renewIdToken doesn't work properly after expireOffsetSeconds has passed. 
The problem is that: STORAGE.STATE_RENEW is never saved on _renewIdToken. Instead you do:
        var frameHandle = this._addAdalFrame('adalIdTokenFrame');
        var expectedState = this._guid() + '|' + this.config.clientId;
        this._idTokenNonce = this._guid();
        **this._saveItem(this.CONSTANTS.STORAGE.NONCE_IDTOKEN, this._idTokenNonce, true);**
        this.config.state = expectedState;

Later on the _matchState function checks STORAGE.STATE_LOGIN and STORAGE.STATE_RENEW and never finds the match.

If I do add the below line into _renewIdToken then the functionality starts working properly:
        var expectedState = this._guid() + '|' + this.config.clientId;
        **this._saveItem(this.CONSTANTS.STORAGE.STATE_RENEW, expectedState, true);**

Sorry if I have not very clear explanation but I think that you can catch the idea.

Thank you in advance

P.S. As always it is quite urgent

**Comment by rohitnarula7176** [comment] 2018-03-01 22:41
@rtarasov When you call _renewIdToken, adal sends the request in a hidden iframe and saves the state on the parent window. We save the state in the browser local/session storage only in the case of loginRedirect or acquireTokenRedirect api.

Please see the below lines of code.
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/703e560f26de90fef9ae955529605672242c1f71/lib/adal.js#L534
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/703e560f26de90fef9ae955529605672242c1f71/lib/adal.js#L1321
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/703e560f26de90fef9ae955529605672242c1f71/lib/adal.js#L1077

You might be using an external adal angular package whose code is not in sync with the latest version of this repo. Closing this issue as this is not a bug in Adal.

**Closed by rohitnarula7176** 2018-03-01 22:41 UTC
