### ISSUE TITLE
Implement Library for Angular2

### ISSUE THREAD

**Issue by zachcarroll** [AzureAD/azure-activedirectory-library-for-js#236] opened 2016-02-23 15:07 UTC
We need a new version of the adal angular library implemented for Angular2.

**Comment by mdocter** [comment] 2016-03-02 11:27
+1 I need it too, but this is a duplicate of #194.

**Comment by tushargupta51** [comment] 2016-03-04 05:55
Closing this one as dup of #194

**Closed by tushargupta51** 2016-03-04 05:55 UTC
