### ISSUE TITLE
after some time redirected to 'The reply URL specified in the request does not match'

### ISSUE THREAD

**Issue by bilalmalik777** [AzureAD/azure-activedirectory-library-for-js#921] opened 2020-09-17 13:15 UTC
We are using adal-angular in reactjs for authentication from the azure ad. After some time it redirects to the page which is attached below
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23011613/93474918-8a523a80-f8e7-11ea-94d5-0e641599380c.png)
We have no idea why is it happening either it is caused by token expiration or re-login. It is occurring over both local and production environment. Even we have registered return url in application in ad
Please help us to solve this issue

**Comment by jasonnutter** [comment] 2020-09-21 18:48
Closing as a duplicate of the issue you posted in the MSAL.js repo.

**Closed as completed by jasonnutter** 2020-09-21 18:48 UTC
