### ISSUE TITLE
Angular 2 / 4 support

### ISSUE THREAD

**Issue by hkusulja** [AzureAD/azure-activedirectory-library-for-js#564] opened 2017-05-30 23:17 UTC
This official repository is stagnating on master.
Please update the "lib/adal-angular.js" and add support for latest stable Angular 2 and Angular 4.

**Comment by aciccarello** [comment] 2017-06-06 15:55
Others have ported support this to Angular. Would be great to see this officially supported:

https://www.npmjs.com/package/ng2-adal
https://www.npmjs.com/package/angular2-adal
https://www.npmjs.com/browse/keyword/adal

**Comment by aciccarello** [comment] 2017-06-06 16:06
This should be considered a duplicate of #194. There @tushargupta51 [states](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/194#issuecomment-252121917):

> We are focusing our efforts towards next generation of adal library - MSAL, which will support AAD, MSA accounts as well as B2C. We will definitely consider Angular 2 for that.

**Closed** 2017-06-06 17:20 UTC
