### ISSUE TITLE
Adal-Angular Infinite loop

### ISSUE THREAD

**Issue by keyurtechy** [AzureAD/azure-activedirectory-library-for-js#419] opened 2016-10-19 19:15 UTC
Hi,

In one of our project we are implementing Adal-Angular along with Asp.Net Core, and we are facing one issue. After the user is authenticated with AAD and after we get the token, the Adal framework is going for an infinite loop. It was not redicrecting the user to the correct view that we have defined in our angular routing framework.

https://localhost:44324/#!#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1......

The above url, we will be looping indefinitely. 

As mentioned in one of the github issue related to this infinite loop, it has been asked to use 1.0.11 adal package and we are using the same. We are not facing this issue in all the systems. We are facing this issue in few machines and we wanted to know the root cause of this issue and we need some permanent solution.

Tried below solutions but not working..

1) We tried even with the information that has been provided at the below github https://gist.github.com/tushargupta51/5fa6d000357120adbc8fd1d5c68853c4 and it’s not working for us

2) We tried to debug adal angular code, and what we found was, in adal-angular.js, in the method, updateDataFromCache,  _adal.getCachedToken(resource); is returning null

One change we have done in adal.angular.js was, in the $get method, once we get the hash from $window.location.hash;, we have written the following line of code

hash = hash.replace(‘#!’, ‘’), after that infinite loop has stopped, but our application UI has broken

Can anyone suggest solution for loop and !character issue.

**Comment by amitabhm21** [comment] 2016-10-19 19:29
@tushargupta51 suggested to set the hashPrefix when using html5Mode.
   
 // using '!' as the hashPrefix but can be a character of your choosing
    app.config(['$locationProvider', function($locationProvider) {
        $locationProvider.html5Mode(true).hashPrefix('!');
    }]);

**Comment by keyurtechy** [comment] 2016-10-20 23:47
@tushargupta51 This is the log that got generated. Check whether this is going to help you?

Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-VERBOSE: Location change event from https://localhost:44324/#!#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng…-4b31-bcd0-802d018b4731&session_state=933eacb0-43b5-45e5-a82f-a4abcd0fb60a to https://localhost:44324/#!#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng…-4b31-bcd0-802d018b4731&session_state=933eacb0-43b5-45e5-a82f-a4abcd0fb60a
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: State change event for:#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ikk2b0J3NFZ6QkhPcWxlR3JWMkFKZEE1RW1YYyIsImtpZCI6Ikk2b0J3NFZ6QkhPcWxlR3JWMkFKZEE1RW1YYyJ9.eyJhdWQiOiJiOTRmMDdkZi1jODI1LTQzMWYtYjljNS1iOTQ5OWU4ZTlhYzEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zYzQ1NjJjYS0zOWE0LTRkOGItOTFmZi02ZDNlZWZhYjVjMWQvIiwiaWF0IjoxNDc3MDA2NzY2LCJuYmYiOjE0NzcwMDY3NjYsImV4cCI6MTQ3NzAxMDY2NiwiYW1yIjpbInB3ZCJdLCJmYW1pbHlfbmFtZSI6IkdhamFybGEiLCJnaXZlbl9uYW1lIjoiV2lsc29uIiwiaXBhZGRyIjoiMTMxLjEwNy4xNjAuNTYiLCJuYW1lIjoiV2lsc29uIEdhamFybGEiLCJub25jZSI6ImY2YTQzNjBkLTIwZjQtNDI0ZC04MzE0LTdjNTJiM2I3MTVlMiIsIm9pZCI6IjkzM2NlMWZkLTI2OTMtNGFhZS1iN2JhLTJhMGI2OGU0MTAyOSIsInN1YiI6ImtxZ3l0TENSUVJVY1FNb2hQWEJFQkpIT2dOdms0RVdLQU0wYTNVWWhHcFEiLCJ0aWQiOiIzYzQ1NjJjYS0zOWE0LTRkOGItOTFmZi02ZDNlZWZhYjVjMWQiLCJ1bmlxdWVfbmFtZSI6Im1hdHRlcmFkbWluQE1TbWF0dGVyLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6Im1hdHRlcmFkbWluQE1TbWF0dGVyLm9ubWljcm9zb2Z0LmNvbSIsInZlciI6IjEuMCJ9.Tg-SqTDIDM1PnmpOaKb4V8myMAgUEN2MXoPqMzHJIypCCVq_sLJgxKdTtMZUq3jSpW3dR3PenrIUkmmJcfurrXL26xx355AIyi0Rk8FyTf-o0JiBlq3jGthDVEdX0QQG-b_6gCJOhftUDfapiM5kPrJ7vdhZXqVPgFj2SITmMsRRE2_E7XKH76hvd69gIMqcW3wSClr5JC5YXFRzSzH6r8KJOr3kNMD5p0CWhuxs30JqUaFUiuXB8xuBSVg0kCdJACTfStV1g66kw8uZj4vsny4A3BO4qHFL-Stzu2_kjYuPrnehOAAhYm_iQSBh9e_d9rekB2G7SXGPWlxbXi-DKA&state=11978c99-4d42-4b31-bcd0-802d018b4731&session_state=933eacb0-43b5-45e5-a82f-a4abcd0fb60a
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: Login event for:#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ikk2b0J3NFZ6QkhPcWxlR3JWMkFKZEE1RW1YYyIsImtpZCI6Ikk2b0J3NFZ6QkhPcWxlR3JWMkFKZEE1RW1YYyJ9.eyJhdWQiOiJiOTRmMDdkZi1jODI1LTQzMWYtYjljNS1iOTQ5OWU4ZTlhYzEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zYzQ1NjJjYS0zOWE0LTRkOGItOTFmZi02ZDNlZWZhYjVjMWQvIiwiaWF0IjoxNDc3MDA2NzY2LCJuYmYiOjE0NzcwMDY3NjYsImV4cCI6MTQ3NzAxMDY2NiwiYW1yIjpbInB3ZCJdLCJmYW1pbHlfbmFtZSI6IkdhamFybGEiLCJnaXZlbl9uYW1lIjoiV2lsc29uIiwiaXBhZGRyIjoiMTMxLjEwNy4xNjAuNTYiLCJuYW1lIjoiV2lsc29uIEdhamFybGEiLCJub25jZSI6ImY2YTQzNjBkLTIwZjQtNDI0ZC04MzE0LTdjNTJiM2I3MTVlMiIsIm9pZCI6IjkzM2NlMWZkLTI2OTMtNGFhZS1iN2JhLTJhMGI2OGU0MTAyOSIsInN1YiI6ImtxZ3l0TENSUVJVY1FNb2hQWEJFQkpIT2dOdms0RVdLQU0wYTNVWWhHcFEiLCJ0aWQiOiIzYzQ1NjJjYS0zOWE0LTRkOGItOTFmZi02ZDNlZWZhYjVjMWQiLCJ1bmlxdWVfbmFtZSI6Im1hdHRlcmFkbWluQE1TbWF0dGVyLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6Im1hdHRlcmFkbWluQE1TbWF0dGVyLm9ubWljcm9zb2Z0LmNvbSIsInZlciI6IjEuMCJ9.Tg-SqTDIDM1PnmpOaKb4V8myMAgUEN2MXoPqMzHJIypCCVq_sLJgxKdTtMZUq3jSpW3dR3PenrIUkmmJcfurrXL26xx355AIyi0Rk8FyTf-o0JiBlq3jGthDVEdX0QQG-b_6gCJOhftUDfapiM5kPrJ7vdhZXqVPgFj2SITmMsRRE2_E7XKH76hvd69gIMqcW3wSClr5JC5YXFRzSzH6r8KJOr3kNMD5p0CWhuxs30JqUaFUiuXB8xuBSVg0kCdJACTfStV1g66kw8uZj4vsny4A3BO4qHFL-Stzu2_kjYuPrnehOAAhYm_iQSBh9e_d9rekB2G7SXGPWlxbXi-DKA&state=11978c99-4d42-4b31-bcd0-802d018b4731&session_state=933eacb0-43b5-45e5-a82f-a4abcd0fb60a
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: Start login at:https://localhost:44324/#!#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng…-4b31-bcd0-802d018b4731&session_state=933eacb0-43b5-45e5-a82f-a4abcd0fb60a
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-VERBOSE: Expected state: 6f59f0f6-98df-46d3-9f30-898045cb76d6 startPage:https://localhost:44324/#!#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng…-4b31-bcd0-802d018b4731&session_state=933eacb0-43b5-45e5-a82f-a4abcd0fb60a
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: Navigate url:https://login.microsoftonline.com/msmatter.onmicrosoft.com/oauth2/authorize…d=ea7feb26-7f89-4e8d-8412-98d230b64bfd&x-client-SKU=Js&x-client-Ver=1.0.12
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: Navigate to:https://login.microsoftonline.com/msmatter.onmicrosoft.com/oauth2/authorize…ient-SKU=Js&x-client-Ver=1.0.12&nonce=01ff509c-4edc-46cf-bde5-973a39da0419
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-VERBOSE: Url: /app/home.html maps to resource: b94f07df-c825-431f-b9c5-b9499e8e9ac1
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: login is in progress.
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":{},"headers":{"Accept":"text/html"},"url":"/app/home.html","data":"login in progress, cancelling the request for /app/home.html"}
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-VERBOSE: State change error occured. Error: {"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":{},"headers":{"Accept":"text/html"},"url":"/app/home.html","data":"login in progress, cancelling the request for /app/home.html"}
app.js:23 Thu, 20 Oct 2016 23:44:27 GMT:1.0.12-INFO: Setting defaultPrevented to true if state change error occured because adal rejected a request. Error: login in progress, cancelling the request for /app/home.html

**Comment by serverOverload** [comment] 2016-10-22 06:08
another suggestion is to go to your AAD manifest and change the variable for oauth2AllowImplicitFlow to true. It is set as false by default. This grants your application with an implicit OAuth grant, which is needed to handle the hashPrefix of the location provider.

**Comment by tushargupta51** [comment] 2016-10-31 18:46
Update: We debugged this issue using logs and traces and found that somehow "#!" gets added at application level. Comparing working and non-working cases, presence of "#!" in the url is the only difference. Since adal js does not modify these urls, this seems to be an issue either in the application or the reply url registered with AzureAd.

**Comment by tushargupta51** [comment] 2016-11-09 03:41
Closing this issue since '#!' is added at the application level. Adal Js does not modify the reply urls. anuglar.js needs to be debugged to find the root cause.

**Closed by tushargupta51** 2016-11-09 03:41 UTC
