### ISSUE TITLE
Error on acquireToken: User account identifier is not provided

### ISSUE THREAD

**Issue by istrau3** [AzureAD/azure-activedirectory-library-for-js#267] opened 2016-04-19 14:34 UTC
Not sure how to debug this one. I am calling:
```javascript
authContext.acquireToken()
```
in cases where the token is expired and it really does need to go back and refresh from microsoft, it throws me this error. It doesn't even send a request to microsoft for the refresh. Something is erroring out in the library itself.

For what its worth, I am not using angular. Instead, only using libs/adal.js. I get a context by:
```javascript
var authContext = new window.AuthenticationContext(config);
```

Would greatly appreciate some help on this one. As I understand, I am allowed to refresh tokens up to 90 days or something  like that. Is that correct?

**Comment by gabbsmo** [comment] 2016-04-25 07:16
I have the same issue while using the Angular module.

**Comment by PavelPikat** [comment] 2016-04-25 07:23
I had this error when tried running my Angular app from Chrome v50 on OS X with 'Block 3rd party cookies and site data' setting enabled.

**Comment by gabbsmo** [comment] 2016-04-25 07:42
@PavelPikat me too https://github.com/andrewconnell/sp-o365-rest/issues/2

**Comment by istrau3** [comment] 2016-04-25 14:22
@gabbsmo So are you saying that if I publish an app that uses adal then every user that does not have third party cookies enabled won't be able to use my site until they enable them?

**Comment by PavelPikat** [comment] 2016-04-25 14:25
@istrau3 Yes. Because ADAL uses iFrame and it passes cookies through it

**Comment by istrau3** [comment] 2016-04-25 14:30
@PavelPikat Thanks, I just checked and I have third party cookies enabled. Still getting this error though. However, I just checked the resources tab and it looks like I don't have any cookies set. Here is my login code:

```javascript
authContext.login();
```

Am I supposed to be manually saving the cookie or something?

**Comment by istrau3** [comment] 2016-04-25 14:34
@PavelPikat I just looked through the code and I don't see it using cookies explicitly. I have adal data saved in my local storage... When you refer to adal using cookies, is that because you have chosen cookies as your method of storage?

**Comment by PavelPikat** [comment] 2016-04-25 14:39
@istrau3 No, sorry, I'm not 100% sure about what I'm saying. I know you can't see cookies directly in resource tab, but I assume they are used somehow by the iframe to pass states between ADAL library and Azure AD or something like that. That's the only way I can explain why everything breaks if you block 3rd party cookies in Chrome.

**Comment by istrau3** [comment] 2016-04-25 14:53
@PavelPikat Well, I'd think that what you are blocking is third party data, including the ability for third party sites to store information in your session/local storage. In any case, @gabbsmo 's solution does not solve my situation. I am still getting the error when trying to renew the token.

**Comment by tushargupta51** [comment] 2016-04-27 02:59
@istrau3 

> It doesn't even send a request to microsoft for the refresh. Something is erroring out in the library itself.

The "User account identifier is not provided" error is send by AAD when ADAL requests a token. Adal itself does not create any cookies but AAD saves cookies after authenticating user. These cookies must be present in the request that ADAL sends to renew tokens.

Which browser are you seeing this issue for? Can you provider a fiddler trace or logs to help investigate into this further?

**Comment by sandor11** [comment] 2016-04-28 05:12
@tushargupta51 I have this error for the `RENEW_TOKEN` request on `Chrome 49.0.2623.112 m`

[adal-log.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/239841/adal-log.txt)

**Comment by sandor11** [comment] 2016-04-28 14:23
@tushargupta51 I have discovered this error was occurring because I was somehow logged out of my Azure AD Account, once I logged back in with the KMSI option selected I was able to retrieve a refresh token.

**Comment by gabbsmo** [comment] 2016-04-28 14:55
@sandor11 What do you mean by KMSI? Did you manage to login again from your app or somewhere else?

**Comment by istrau3** [comment] 2016-04-28 19:29
@tushargupta51 I am seeing this issue in chrome. 

I went to https://login.microsoftonline.com and checked my resources tab. There are cookies saved there. I guess my browser should be sending these cookies along with the request. 

The problem with this issue is that it is not easy to reproduce. I need to wait for my token to expire because it only happens on token renewal not on initial login. 

That said, next time I am able to reproduce what would you like me to post? I mean, can you expand on "fiddler trace" and "logs" (so that I can produce them for you)?

**Comment by tushargupta51** [comment] 2016-04-28 19:36
@istrau3 logs will help

**Comment by istrau3** [comment] 2016-04-28 19:40
@tushargupta51 Yes, but what do mean by that? How do I produce those? I have fiddler on my machine, how do I get a 'fiddler trace'? By log do you mean the browser's stack trace in the console?

**Comment by tushargupta51** [comment] 2016-04-28 20:03
@istrau3 You can add this to your app.js. This will generate console logs in the browser:
Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    }
};

Have fiddler running on your machine when you interact with your web app to reproduce. Once you are done, save the captured output in fiddler.

**Comment by sandor11** [comment] 2016-04-29 00:02
@gabbsmo Keep Me Signed In (KMSI) check box option when logging in to your Azure Management Console, or other Microsft related sites. This option is not present on the App Login screen however.

The issue here was that I was trying to retrieve an access token for a user in my app who was not logged in to their Microsoft Account, and I believe this behavior is correct.

@tushargupta51 In relation to this, why are we seeing an error message at all? Why isn't it possible to detect the user is not signed into their Microsoft account and redirect them to do so at an appropriate site? I realize the `adal.js` login code directs them to sign into our App, but why cant they be told they are not currently logged in to their Microsoft Account and choose to log in with (KMSI) option?

@istrau3 When debugging this issue, I would simply change my system clock settings to be 2 hours post login which would then cause the `adal.js` code in my browser to believe the token was expired. If that is of any help.

**Comment by istrau3** [comment] 2016-05-02 14:31
@tushargupta51 

Update: I came into work this morning and I am seeing the same behavior. There is no network call that goes out (in fiddler or in the chrome network tab).

I stepped through the code.

Here is where it fails:

```javascript 
AuthenticationContext.prototype.acquireToken = function (resource, callback) {
    if (this._isEmpty(resource)) {
        this.warn('resource is required');
        callback('resource is required', null);
        return;
    }
    
    var token = this.getCachedToken(resource);
    if (token) {
        this.info('Token is already in cache for resource:' + resource);
        callback(null, token);
        return;
    }
    
    if (this._getItem(this.CONSTANTS.STORAGE.FAILED_RENEW)) {
        this.info('renewToken is failed for resource ' + resource + ':' + this._getItem(this.CONSTANTS.STORAGE.FAILED_RENEW));
        callback(this._getItem(this.CONSTANTS.STORAGE.FAILED_RENEW), null);
        return;
    }

//this.CONSTANTS.STORAGE.FAILED_RENEW === "adal.failed.renew"

```

**Comment by PavelPikat** [comment] 2016-05-11 07:22
I encountered the same problem as @istrau3 this morning when I came back to work and had stored tokens in the localStorage from yesterday's session. 
Adal tried to send a request to login.microsoftonline.com with response_type=id_token. It sent my client_id, state, login_hint and nonce as params, but got 302 Redirect to 
`Location: http://localhost:3000/launcher.html#error=login_required&error_description=AADSTS50058%3a+User+account+identifier+is+not+provided.%0d%0aTrace+ID%3a+5dec95fc-02f7-4c04-983d-890b62c83e51%0d%0aCorrelation+ID%3a+0047258a-fe12-45f9-afda-51f3d940fb4e%0d%0aTimestamp%3a+2016-05-11+07%3a19%3a00Z&state=626c4e5b-c225-447d-9865-a446f28c0fcd%7c134d2747-05f2-4d0d-b38a-7101361c2b64`

**Comment by tushargupta51** [comment] 2016-05-11 17:29
@PavelPikat Did you re-open the browser? If AAD cookie is expired, it will show this error.

**Comment by nataliavalgepea** [comment] 2016-05-11 19:24
@tushargupta51 Yes, my computer was off :) Should we manually handle this error and redirect the user to the login screen?

**Comment by PavelPikat** [comment] 2016-05-11 19:25
@tushargupta51 Yes, my computer was off :) Should we manually handle this error and redirect the user to the login screen?

**Comment by tushargupta51** [comment] 2016-05-11 20:04
@PavelPikat If the browser was closed, and you re-open the browser after the tokens saved in localStorage are expired (> 1 hr), then user would need to login back again. Maybe its worth to revive #272 , I am working with an internal team to get this sorted out. It seems that web apps that are using adalJs and are not hosted inside a web view on a mobile device, should see the KMSI checkbox by default. Though thats not the case right now, and we are working with AAD team to get a better understanding of what is happening.

**Comment by PavelPikat** [comment] 2016-05-12 10:57
**How to reproduce:** (I am using Chrome and adal-angular 1.0.10, storage set to localStorage)

1. Login to Angular app in one tab
2. Open https://login.microsoftonline.com/ in another tab
3. Clear cookies for https://login.microsoftonline.com/
4. Clear localStorage for angular app
5. Trigger route change/refresh angular app

**Comment by tushargupta51** [comment] 2016-05-12 20:18
@sandor11 There are 2 flavors of acquireToken - interactive and silent. Adal js only implements silent flow ATM which means if renew token operation fails, it does not prompt user to enter credentials, it will send an error and then developer can decide what to do with it. Developers need to call _adal.login for prompting the users to login. We plan to add the interactive version too, I think it is in experimental branch.

@PavelPikat If you clear the cookies, then this error is expected, its not a bug then. Since adal cannot renew token if there is no valid cookie sent along with the request. And as it is a silent renewal, it wont prompt user to log back in again unless `login()` method is called.

**Comment by tushargupta51** [comment] 2016-05-12 20:21
I don't think this issue is a bug in ADAL, "User account not identifier" is an expected error when adal tries to renew the token and there is no valid aad authentication cookie sent along with the request. This error is sent from AAD. To recover from this error, users need to log back in again.

Also, we are in process of fixing the missing KMSI checkbox, that will keep the aad cookie for longer time and not just until browsing session. Though keep in mind, that KMSI option wont be available for hosted flows.

I am inclined towards closing this issue. Please let me know if anyone has any concerns.

**Comment by gabbsmo** [comment] 2016-05-13 07:17
@tushargupta51 are you refering to the adal:loginFailure event in adal-angular? Handling that event is clearly marked as optional in the README.

**Comment by PavelPikat** [comment] 2016-05-13 07:49
@tushargupta51 I get your point. I actually fixed it for us by handling adal:loginFailure event and forcing the user to login again. And I agree that this issue is not really a bug, but a lot of users seem to be confused about it.

**Comment by tushargupta51** [comment] 2016-05-13 18:00
@gabbsmo Well, its optional if you dont want to deal with errors and recover from an error scenario. Its not required unless you want to handle an error.

**Closed** 2016-05-13 18:21 UTC
Labels: Investigating

**Comment by viganella** [comment] 2018-06-12 20:11
I think this is clearly a bug, i followed the discussion thoroughly that happened  here and it seemed that we lost the point.
Token is not refreshing by default how it is supposed to be (using refresh_token and hidden iframe <- which i do not even know how to debug it), and when using acquireToken method (i tried to trigger every 20 minutes for debugging purposes) in 1 hour token has expired and instead of using iframe to get a new one i get a 'login is required ' message back, which i know how to handle but we suppose not to get this message. 
We supposeed to have a new access_token when the previous has expired. 
I have enabled cache, I have check KMSI but problem persists.
I do not want to stop user and my websocket connection every 1 hour, is disaster for me.
