### ISSUE TITLE
Add support for Angular UI Router 1.x

### ISSUE THREAD

**Issue by PhilDore11** [AzureAD/azure-activedirectory-library-for-js#591] opened 2017-07-14 15:29 UTC
Using latest version of ```angular-ui-router@1.0.5```, adal-angular is throwing console errors when trying to fetch template files.

Also, the ```requireADLogin``` doesn't seem to work.

**Comment by aciccarello** [comment] 2017-08-10 00:01
Duplicate of #574

**Comment by jmprieur** [comment] 2017-09-03 20:11
Closing a a duplicate

**Closed by jmprieur** 2017-09-03 20:11 UTC
Labels: Duplicate
