### ISSUE TITLE
requireADLogin without routing?

### ISSUE THREAD

**Issue by shahjinesh11** [AzureAD/azure-activedirectory-library-for-js#575] opened 2017-06-19 09:14 UTC
It works fine with routing but I am not using ngRoute in my application. 

then how can i handle requireADLogin in .config?

**Comment by rohitnarula7176** [comment] 2017-06-21 09:33
@shahjinesh11 The library requires ng-route or ui.router to handle requireADLogin. Thats the only way for us to know whether the route is protected and requires a token.

**Comment by jmprieur** [comment] 2017-06-22 08:10
Closing as by design
@shahjinesh11 : did you try to use ADAL.js with plain JavaScript (without Angular?)

**Closed by jmprieur** 2017-06-22 08:10 UTC

**Comment by shahjinesh11** [comment] 2017-06-22 08:25
With Plain JavaScript, its working fine. But I wanted to use with angular only.

Thanks for the help.
