### ISSUE TITLE
When id_token is !#id_token isCallback() function returns false

### ISSUE THREAD

**Issue by eloekset** [AzureAD/azure-activedirectory-library-for-js#485] opened 2017-02-09 14:14 UTC
I'm having an issue with the return url from Azure AD, and I'm not sure why it happens.

When the id_token is returned with an exclamation mark in front of the hash sign, adal's isCallback function returns false since it doesn't match the CONSTANTS.ID_TOKEN value.

![id_token](https://cloud.githubusercontent.com/assets/791721/22786767/2de8ff56-eeda-11e6-91b0-5ba9c5ba46ab.png)

I've not been able to find any information about it, so I'm opening this issue to see if anyone knows what's going on when this happens.

**Comment by tushargupta51** [comment] 2017-02-09 21:13
@eloekset Do you set the `$locationProvider.hashPrefix`? Adal does not add "!" to the url. Is there any custom logic in application that might affect this?

**Comment by eloekset** [comment] 2017-02-10 08:23
I'm following a Pluralsight course "Azure AD for Developers" and the code is really simple. I don't do anything with the `$locationProvider.hashPrefix` myself, but I tested the code from the Exercise Files downloaded from the course, and that worked. This is a screenshot of the URL in the video:
![2017-02-10_0857](https://cloud.githubusercontent.com/assets/791721/22819317/dbd81506-ef71-11e6-9a3b-3991d794809d.png)

So I copied in the **angular.min.js**-file used in the course project to my own project, and now I don't get the **#!#** part of the URL anymore. Since both the course material and my project use the minified version of **angular.js**, I'm not able to see what the differences are, but maybe your guess is correct, @tushargupta51. 

Anyway this indicates that there's an issue when using the latest version of **angular.js**.

**Comment by eloekset** [comment] 2017-02-10 09:11
I reproduced the issue using **adal-angular.js** v1.0.13 and **angular.js** v1.6.1 in this repo: https://github.com/eloekset/AngularAdalIssue485

**Comment by tushargupta51** [comment] 2017-02-16 20:35
@eloekset Can you share a fiddler trace with the requests and responses from AAD?

**Comment by eloekset** [comment] 2017-02-17 10:09
Thanks, @tushargupta51! I've sent you an email with the fiddler trace details.

**Comment by tushargupta51** [comment] 2017-02-17 18:52
@eloekset In the fiddler trace, frame #24 and 49 have the correct url without the "!" sign. Did everything work fine when you captured the fiddler trace? Also, can you try reproducing the bug with 1.5.x and 1.6.1 version and see if that makes any difference. If it does, then its an issue in angular routing.

**Comment by eloekset** [comment] 2017-02-17 19:15
Yes, the URL from Azure AD looks correct, but the repro project fails every time. I'm not using Angular in any of my projects, just this project from the Pluralsight course, so I'm not enough into Angular to guess why it happens. When I use Adal-js without Angular, it works fine.

**Comment by tushargupta51** [comment] 2017-02-17 19:19
@eloekset If I understand correctly, in the sample code here: https://github.com/eloekset/AngularAdalIssue485, the angular version used is 1.6.1 and it reproduce the issue and I guess the fiddler trace you provided is from the same sample.

What we can try next is to use 1.5.8 version of angular and see if still repro the issue or not. This does not seem like adal issue to me since we do not append "!" anywhere in our code. If its getting added after AAD sends response (as it seems in this case), its most likely that client side routing is playing a role here.

**Comment by eloekset** [comment] 2017-02-18 10:18
The Fiddler trace I sent you is from this sample.

I can confirm that it works fine when downgrading Angular from 1.6.1 to 1.5.9. I've done this in a PR in the sample repo: https://github.com/eloekset/AngularAdalIssue485/pull/1

![2017-02-18_11-11-48](https://cloud.githubusercontent.com/assets/791721/23092471/e38815ac-f5cb-11e6-8550-4fd814d8b010.png)

So right now AdalJS doesn't work out of the box with the latest Angular 1.X.

**Comment by tushargupta51** [comment] 2017-02-18 18:42
@eloekset From looking around, it seems Angular made a breaking change:

https://docs.angularjs.org/guide/migration#commit-aa077e8  and
https://github.com/angular/angular.js/commit/aa077e81129c740041438688dff2e8d20c3d7b52

where they changed the default hash prefix from '' to '!'. As they have pointed out, apps that are not using html5 mode, should now specify the default hash prefix to be '' like this:

      appModule.config(['$locationProvider', function($locationProvider) {
        $locationProvider.hashPrefix('');
     }]);

I will close this issue now since this should be set at the application level instead of library level.

**Closed by tushargupta51** 2017-02-18 18:42 UTC

**Comment by eloekset** [comment] 2017-02-18 19:52
Thanks again @tushargupta51! I've tested it and can confirm that it works. I'll update the discussion page of the Pluralsight course in case others need help with this as well.

**Comment by amrlafi** [comment] 2017-02-20 17:17
Thanks for the info. I had the same annoying problem. 
If one wish not to downgrade angular, as advised on https://docs.angularjs.org/guide/migration#commit-aa077e8 , setting hashPrefix to empty fixes the issue.

**Comment by nilMicro** [comment] 2017-03-29 01:02
I have downgrade the angular and its working good.
