### ISSUE TITLE
Portal is loaded twice after login

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#448] opened 2016-11-24 17:32 UTC
Hi All,

While upgrading to the latest version I’ve noticed a bad experience in my portal, the page is loaded after login, but then blinks and loaded again. Taking a look at the outgoing requests, I saw another call to the server while the application is loaded.

I found this code in the adal-angular file, under locationChangeHandler :

```
var loginStartPage = _adal._getItem(_adal.CONSTANTS.STORAGE.LOGIN_REQUEST);
if (typeof loginStartPage !== 'undefined' && loginStartPage && loginStartPage.length !== 0) {
      // prevent the current location change and redirect the user back to the login start page
      _adal.verbose('Redirecting to start page: ' + loginStartPage);
      if (!$location.$$html5 && loginStartPage.indexOf('#') > -1) {
          $location.url(loginStartPage.substring(loginStartPage.indexOf('#') + 1));
      } 
      $window.location = loginStartPage;
}
```

Not sure whether it’s a bug in the code, or something in my app but I have 2 concerns:
1.	The $window.location change causes a full refresh – why do it then in a SPA?
2.	Anyhow – shouldn’t this row be in an “else” clause?

Thanks,
Ido.

**Comment by tushargupta51** [comment] 2016-12-05 21:29
@ischrei Can you share the following:
1. routing library and version
2. angular version
3. Html5 mode on or off
4. console logs for login process.

**Comment by ischrei** [comment] 2016-12-13 22:15
Hi,
1. During authentication we don't use any routing library (ui-router will be loaded after the user is authorized)
2. Angular 1.4.8
3. HTML5 off
4. Will send you logs privately.

Thanks!

**Comment by yarick123** [comment] 2016-12-17 00:56
@ischrei , I do not use angular, but have nearly the same behavior.

As far as I understand, the authorization process consists of several steps. In every intermediate step AuthenticationContext.handleWindowCallback(..) must be called. If the 'popUp' configuration setting is false, that is  default value, window.location is updated (line 988 in ADAL.js 1.0.13). Then the page is reloaded. By me, the page, user visited the first time, is refreshed three times, if the user has not been logged in before. So, I call AuthenticationContext.acquireToken(...) thrice, the 'callback' is also called thrice with a correct token.

I am rebuilding the authentication logic now. One new "StaticLogin"page is created. This page calls all the necessary AuthenticationContext methods to acquire token. If the user has no cached token (AuthenticationContext.getCachedToken(..)), she will be redirected to this "StaticLogin"page. This page is refreshed by ADAL.js as many times as needs. After getting the token, the user is redirected back to the original page.

Regards.

**Comment by ischrei** [comment] 2016-12-18 21:02
Thank you @yarick123. Not sure what you mean by "refreshed as many times as needed", as I see it, only 1 redirection is valid, which is the redirection to AAD in case the user isn't logged-in. Every other refresh, specially for a Single Page Application is a bad behavior and in fact a bug.

BTW, I'm suggesting the following fix:
```
if (!$location.$$html5 && loginStartPage.indexOf('#') > -1) {
    $location.url(loginStartPage.substring(loginStartPage.indexOf('#') + 1));
} else {
    $location.url('');
}
```

**Comment by yarick123** [comment] 2016-12-19 10:01
@ischrei , thank you for your workaround. I will analyze it. Maybe it will also help me, if it is applicable for the non-angular version.

In my case, there are many "refreshes" because every time, as the line 988 is executed, happens a refresh. I see as minimum two causes: the first one, when the page gets the token as an URL parameter; the second one - as the token is removed from the URL. But, as I said - I do not use angular.

**Comment by dliu120** [comment] 2017-03-21 09:14
+1 we are seeing this issue as well. This is happening in 1.0.14 and was happening in 1.0.13

**Comment by cdian** [comment] 2017-04-03 10:14
+1 same problem with 1.0.14 !

**Comment by rohitnarula7176** [comment] 2017-06-29 23:26
@dliu120 @cdian @yarick123 The 2 reloads that you see during login is by design. The first reload is when the redirect response is received with the token attached to the urlHash and the second reload occurs when adal tries to remove the token from the hash and reset the location back to the loginStartPage. Setting $window.location again in the code above, should not cause any additional reload as in angular, triggering the same route twice will not trigger the location change event. Can you guys provide a small repro which shows the additional reload other than the 2 reloads I have mentioned with the above code.

**Comment by yarick123** [comment] 2017-07-01 21:11
@rohitnarula7176 ADAL.js 1.0.13 has reloaded window content thrice by me. ADAL.js 1.0.14 does that twice.

**Comment by jmprieur** [comment] 2017-07-03 16:20
Closing the issue, as reloading twice is expected as @rohitnarula7176 explained. Feel free to reopen.

**Closed by jmprieur** 2017-07-03 16:20 UTC
Labels: Investigating, User Reported
