### ISSUE TITLE
Chopping parameter after authenticating URL from Azure AD

### ISSUE THREAD

**Issue by bhatnagar-anuj** [AzureAD/azure-activedirectory-library-for-js#256] opened 2016-04-04 18:45 UTC
While passing the parameter in the URL (deep url), after authenticating from Azure AD, it's returning the URL after chopping the parameters.

E.g. Incase I’m sending URL with parameter 5  ‘https://foo.azurewebsites.net/foo.html#/5’ it’s chopping 5 and returns ‘https://foo.azurewebsites.net/foo.html#/ ‘. 

Any Solution ??

**Comment by PavelPikat** [comment] 2016-04-04 18:51
If you are talking about reply uri parameter passed to AAD on login, then it's not possible, because AAD will ignore everything after #, because it's using it to pass tokens back.

**Comment by bhatnagar-anuj** [comment] 2016-04-04 19:47
We are using this for parametrized routes e.g. deep url. e.g. /Report/ReportId. In that case user should be authenticate and come back to the application with the same parameter what he had passed during the Origin.

**Comment by PavelPikat** [comment] 2016-04-04 20:30
It's not possible with AAD return uri. 
We are saving user's current state in session\localStorage before adal redirects to AAD, then restoring the state from storage after the token has been obtained.

**Comment by dstrockis** [comment] 2016-04-05 16:26
@PavelPikat is right.  Adal should take care of the storage & redirect for you though.  I think there are already a couple of open issues on the matter.

**Comment by tushargupta51** [comment] 2016-05-13 00:49
@bhatnagar-anuj To make sure I understand the issue correctly, user navigates to a state/url e.g. /Report/ReportId which requires authentication. User is redirected to login. After login, the user is not redirected back to original url/state from where the login started: /Report/ReportId. Is that correct? Or are you talking about the parameters that you included in the return uri when sending request to AAD? If latter, then AAD strips off everything after "#" before it returns back the token to the app.

**Comment by PavelPikat** [comment] 2016-05-13 08:06
I think it's also important to know which router people use.

For example, we use ui.router and we had a similar issue with Adal - it didn't redirect back to the correct state after login, so we customized adal-angular source and added an extra parameter to store in the storage:

`_adal._saveItem('adal.start.page.state', toState.name)`

And then we use this value in locationChangeHandler.
I could probably share our custom adal-angular 1.0.10, let me know, @tushargupta51

**Comment by tushargupta51** [comment] 2016-05-13 18:04
@PavelPikat Sure, please share the custom changes you made. I was able to reproduce all of the routing parameters related issues locally using ui-router and stateProvider. We need some modifications to what we save and how we rebuild state, stateParams and url from that.

**Comment by bhatnagar-anuj** [comment] 2016-05-16 03:46
**@tushargupta51** user navigate to a  state/Url (e.g. http://localhost:4050/Report.html#/5) which required authentication. User redirect to login and after login user redirect to http://localohost:4050/Report.html#/.
Hence chopped everything after #.

**Comment by bhatnagar-anuj** [comment] 2016-05-16 03:50
**@tushargupta51** : Do you have any tentative timeline for the fix ?

**Comment by tushargupta51** [comment] 2016-05-16 04:58
@bhatnagar-anuj we plan to ship out fix for this in next release, which is tentatively mid June.

**Comment by polita** [comment] 2016-05-16 18:22
Duplicate root cause of #130

**Closed by polita** 2016-05-16 18:22 UTC
Labels: 1 - Working

**Comment by antoniocvaraujo1** [comment] 2018-01-12 17:24
@PavelPikat , i'm facing this issue with angular js.
could you share your solution with me ?
Thanks in advance.

**Comment by viganella** [comment] 2018-03-03 17:41
I have a very similar issue, where the user goes to a specific route project/:projectId then it is redirected for login to Azure portal, after authentication he goes to auth-redirect route, and at this route I need to know the projectId that I initially requested to access so I can direct the user at the right place!!
Should  'state' parameter take care of this, or does anybody else have a more innovative solution ?

**Comment by hkusulja** [comment] 2018-04-05 10:13
Hash / fragment url is not supported by OAuth2 / RFC standard to be in part of redirect url.
But if you are using routes like https://localhost:1234/projectId/4  , as return url it should work.

However, Azure AD application requires that concrete and absolute url is registered as reply url, so it is not possible to dynamically change url path / parameters.
I do not know, why and where is this documented.

This is not related to ADAL / MSAL, this is for web login page on Azure AD side...
