### ISSUE TITLE
Adal.js acquireToken fails with invalid state error in a React project

### ISSUE THREAD

**Issue by lyyjohn45** [AzureAD/azure-activedirectory-library-for-js#701] opened 2018-01-16 18:58 UTC
Hello,

I used adalJs in adal-angular npm to fetch a token for a web api. It has been working for months but it suddenly started to fail around Dec/20th/2017.

The adal returns error message:
Invalid_state. state: 370fe0df-43ab-4330-a3b6-340fef8b3299|4e92b890-ad03-43cf-bd61-585b3eb353d5

The exception happens when the acquireToken method is called. I am using the example from https://blog.mastykarz.nl/building-office-365-web-applications-react/ to use react with adaljs.

![screenshot 152](https://user-images.githubusercontent.com/1646833/35006690-15057aa8-faac-11e7-85ad-34ee1afadec4.png)

There is also a person who has same exact issue as me reported in stackoverflow: https://stackoverflow.com/questions/47899429/adaljs-acquiretoken-fails-with-invalid-state-error

**Comment by rohitnarula7176** [comment] 2018-01-16 20:59
@lyyjohn45 The issue is because the sample you are referring to needs to be updated as per the latest version of Adal 1.0.16. I was able to fork the repo and submit a pull request to the owner to fix the invalid_state issue. Please refer to the link below to see the code changes:
https://github.com/waldekmastykarz/office-mygroups-react/pull/3/files
Closing this issue as this is not a bug in the library. Please reopen if you still face any issues.

**Closed by rohitnarula7176** 2018-01-16 20:59 UTC

**Comment by lyyjohn45** [comment] 2018-01-16 23:49
Updated the latest version of adal-angular pkg (1.0.16). And applied @rohitnarula7176 's pull changes to the code, which fixed the issue.
