### ISSUE TITLE
Initial acquireToken always fails.  

### ISSUE THREAD

**Issue by paulwillen** [AzureAD/azure-activedirectory-library-for-js#557] opened 2017-05-22 19:36 UTC
Hello, 

I'm using the ADAL.js to receive the Azure ID of the logged in user in SharePoint Online.
Situation: I'm on a SharePoint Page in SharePoint Online and in this page I'm trying to get the Response.Id from the AJAX call (see code below)

Always when I go to this page the first time the response.id is empty, because somehow ADAL couldn't perform the authContext.login(); function correctly. When I hit refresh, somehow the token is available and I don't need to signin any further and the response.id is a valid value which I can build the rest of my solution on.

Could you please help me to solve the problem for not needing a refresh?
I'm using the latest version of ADAL.js
An excerpt from my code.

		var variables = {
			// Domain of Azure AD tenant
			azureAD: "tenant.onmicrosoft.com",
			// ClientId of Azure AD application principal
			clientId: "xxx-xxx-xxx-xxx-xxx",
					
			// Name of SharePoint tenant
			sharePointTenant: "tenant"
		}			
		// Create config and get AuthenticationContext
		window.config = {	
			tenant: variables.azureAD,
			clientId: variables.clientId,
			postLogoutRedirectUri: window.location.origin,
			endpoints: {
				graphApiUri: "https://graph.microsoft.com",
				sharePointUri: "https://" + variables.sharePointTenant + ".sharepoint.com/sites/sitecollection",
			},
			cacheLocation: "localStorage"
		};
					
		var authContext = new AuthenticationContext(config);
		
		var isCallback = authContext.isCallback(window.location.hash);
		authContext.handleWindowCallback();
		
		if (isCallback && !authContext.getLoginError()) {
			window.location = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
		}
		
		var user = authContext.getCachedUser();
		if (!user) {
			authContext.login();
		}
					
		// Get user information of current user with AuthenticationContext of Graph API 
		authContext.acquireToken(config.endpoints.graphApiUri, function (error, token) {
			if (error || !token) {
				console.log("ADAL error occurred: " + error);
				//debugger;
				throw new Error("Something went badly wrong!");
			}
			else 
			{
				var currentuserUri = config.endpoints.graphApiUri + "/v1.0/me";
				
				$.ajax({
					type: "GET",
					url: currentuserUri,
					async: false,
					//cache: true,					
					headers: {
						"Authorization": "Bearer " + token
					},
					
					success:function(response){..........

the value I try to get in the AJAX call is the `response.id`

**Comment by paulwillen** [comment] 2017-05-31 08:36
Wow - too bad to see that this hasn't got any feedback after 9 days!
I've been on this for a couple of days and the problem is that I was using the latest version 1.0.14.

Switching back to version 1.0.13 solved my problem. Thus 1.0.14 is not backward compatible....

**Comment by rohitnarula7176** [comment] 2017-06-07 18:26
@paulwillen I apologize for the late response. I was OOF for the last couple of weeks. Can you share a working demo of the code so I can investigate this further?

**Comment by paulwillen** [comment] 2017-06-08 07:08
I wrote down a bunch of my code...
A simple example of where version 1.0.14 doesn't work and 1.0.13 does work can be found here: 

julieturner.net/2017/01/extending-sharepoint-with-adal-and-the-microsoft-graph-api-part-2-the-authorization/

**Comment by eoverfield** [comment] 2017-06-09 02:49
I too am witnessing this issue with 1.0.14 when added to SPO and I can also attest that Julie's post is a great example. Very easy to add to a SPO page.

Upon the first load, the redirections occur as they should but the final handle callback doesn't appear to trigger the redirect as it did in 1.0.13.

i.e.
authContext.handleWindowCallback();

I reviewed the changelog and couldn't find any obvious change. I saw others suggest adding a call to authContext.getCachedUser(); right after the callback handler, but that didn't seem to solve the issue.

Any suggestions would be appreciated.

**Comment by rohitnarula7176** [comment] 2017-06-12 17:07
@eoverfield @paulwillen The issue is not that the initial acquireToken always fails but the issue is that when the app is loaded, initial acquireToken request is not sent out. The issue is with the way the sample is written. The sample written by julie turner relies on the third reload of adal to make the call to acquireToken. We made a change in 1.0.14 to prevent the third reload when you login using adaljs to improve performance. Please replace the $document.ready code in julie turner's sample with the one below and the issue will get resolved:
```
 $(document).ready(function () {
        // Check For & Handle Redirect From AAD After Login or Acquiring Token
        var isCallback = sympraxis.authContext.isCallback(window.location.hash);
        if (isCallback)
            sympraxis.authContext.handleWindowCallback(window.location.hash);

        var user = sympraxis.authContext.getCachedUser();
        if (!user) {
            //Log in user
            sympraxis.authContext.login();
        } else {
            sympraxis.getGraphData();
        }

    });
```

**Comment by rohitnarula7176** [comment] 2017-06-12 19:42
@eoverfield @paulwillen I agree that this change in 1.0.14 might break a lot of users relying on the third reload during login. I have made a fix for this issue in the dev branch and it will be part of our next release 1.0.15 which will be sometime this week. Can you please use the dev branch and confirm if this issue is resolved for you.

**Comment by eoverfield** [comment] 2017-06-15 13:32
@rohitnarula7176 Thanks. by using the updated code pattern you provided above and the patch found in commit: https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/54c7c270faa53f2e140d5dd0f65f5cf5aa9caa4f, I was able to get 1.0.14 with commit to work as expected.

**Comment by rohitnarula7176** [comment] 2017-06-16 01:20
Fixed in dev

**Closed by rohitnarula7176** 2017-06-16 01:20 UTC
Labels: 2 - Done
