### ISSUE TITLE
Release 1.0.10 asks for authentication

### ISSUE THREAD

**Issue by sjaanus** [AzureAD/azure-activedirectory-library-for-js#281] opened 2016-05-10 08:16 UTC
I changed to 1.0.10 and now it keeps popping up this window. In previous version there was no such thing, when it needed to login, it redirected to Azure.

Anything I enter into this box, it does not disappear and keeps popping up.

![authreq](https://cloud.githubusercontent.com/assets/964450/15139778/a98eb83e-16a0-11e6-847d-13f3272f780e.png)

**Comment by tushargupta51** [comment] 2016-05-10 08:25
@sjaanus Can you share console logs and the adal init code?

**Comment by tushargupta51** [comment] 2016-06-08 00:40
@sjaanus I am closing this issue for now. If you still experience this issue, let me know, I will re-open it.

**Comment by sjaanus** [comment] 2016-07-25 07:42
![logs](https://cloud.githubusercontent.com/assets/964450/17093821/34a7be40-5254-11e6-9b7d-451444a25c92.png)

Init is here:

```
adalProvider.init({
			instance: 'https://login.microsoftonline.com/',
			tenant: 'foobar',
			clientId: 'foobar',
			extraQueryParameter: 'nux=1'
		}, $httpProvider);
```

This happens also in the 1.0.11 version. If more info is needed, I will provide everything needed.

**Comment by tushargupta51** [comment] 2016-07-25 17:24
@sjaanus I think the above logs are logged after user was logged in. Can you provide the logs for the login flow also (everything that happens when you enter the url in the browser)? Also, which browser are you seeing this issue? Only one or you have tested this across multiple browsers? I found this for Chrome: http://stackoverflow.com/questions/34143331/chrome-authentication-required-the-server-requires-a-username-and-password

**Comment by sjaanus** [comment] 2016-07-26 09:01
This is chrome, this is the login flow
![2016-07-26_11h56_42](https://cloud.githubusercontent.com/assets/964450/17132049/ba662cae-5328-11e6-8212-10540f37ab94.png)
![2016-07-26_11h56_52](https://cloud.githubusercontent.com/assets/964450/17132048/ba626312-5328-11e6-901e-8d96c3ee53c8.png)
![2016-07-26_11h57_06](https://cloud.githubusercontent.com/assets/964450/17132047/ba61ffd0-5328-11e6-9232-7260c4f741e8.png)

**Comment by tushargupta51** [comment] 2016-07-26 16:36
@sjaanus It seems, from the logs, that adal is prompting you for login only once. In screenshot 2, a token is returned from AAD. I assume you saw a Azure AD login screen and entered your credentials, is that right? Or you entered the creds in the pop-up only? Does this reproduce in firefox/Edge/IE?

**Comment by sjaanus** [comment] 2016-07-26 17:00
I logged in in the morning, it does not ask me to login to Azure again for a while, it has my credentials stored or something. Usually what happens at the moment is that I open my website page, it does these 3 refreshes basically, each of which I posted a screenshot of and then webpage opens, but it also has that small login screen opened, which I do not enter my credentials, because Azure has its own login screen
completely. This does not happen in firefox or IE at the moment.

**Comment by tushargupta51** [comment] 2016-07-26 17:09
@sjaanus I think you might be running into the issue I posted the stackoverflow link about. Adal does not create those pop-up dialogs. And as it does not happen on Firefox or IE, I susspect you have some issues with localhost setup and chrome.

**Comment by rohitnarula7176** [comment] 2016-08-15 18:08
Closing this issue as it seems to be related to chrome and localhost setup.

**Closed by rohitnarula7176** 2016-08-15 18:08 UTC
