### ISSUE TITLE
AADSTS50058

### ISSUE THREAD

**Issue by mohanskumar** [AzureAD/azure-activedirectory-library-for-js#423] opened 2016-10-26 15:48 UTC
encountering the following error often, when trying to login to the app after a while. 

Using Chrome in Mac and session storage.  Adal 1.0.12 and adal-angular 1.0.12.

AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
Trace ID: 3945d3c6-8e19-409e-92a8-5212363eb2b1
Correlation ID: ef302455-d122-4950-9f8e-6ae6345fcdf4
Timestamp: 2016-10-26 15:42:09Z"

**Comment by tushargupta51** [comment] 2016-10-27 02:54
@mohanskumar Please look at these related issues:
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues?q=is%3Aissue+AADSTS50058+is%3Aclosed

**Comment by brphelps** [comment] 2016-10-27 17:19
Just to be clear, we started seeing this issue recently as well. The error message is likely conflating two different cases -- we explicitly added all sites in the passive auth chain to our trusted sites and still see the problem. 

One developer on our side explained that with .12, we're no longer getting a cookie that we still get with .10 -- e.g. this issue is a regression specific to .12. 

Please feel free to engage us internally as well.

**Comment by tushargupta51** [comment] 2016-10-31 18:36
>One developer on our side explained that with .12, we're no longer getting a cookie that we still get with .10 -- i.e. this issue is a regression specific to .12.

@brphelps Can you share logs and fiddler traces? I need to look at the complete network to see if cookie is being set on login or not.

**Comment by tushargupta51** [comment] 2016-11-09 03:44
@mohanskumar Is it still an issue for you? 
@brphelps Based on the internal thread, you need to check the value of domain_hint parameter.

**Comment by mohanskumar** [comment] 2016-11-10 15:18
I am all set. thank you so much. 👍

**Comment by tushargupta51** [comment] 2016-11-10 19:07
@mohanskumar Did you find the cause of the error? What fixed it for you? It might help people running into this issue. I will close the issue.

**Closed by tushargupta51** 2016-11-10 19:07 UTC

**Comment by Felix-Indoing** [comment] 2019-08-06 13:50
I am using react-adal and almost all my users in ios Safari face this issues. I have no idea why it happens. All I can do is to tell my users to clear their browser cache and all the cookies. This is particularly painful. Is there any suggestion on this situation?
