### ISSUE TITLE
Acquire token redirect fails when MFA code is required

### ISSUE THREAD

**Issue by RaniSputnik** [AzureAD/azure-activedirectory-library-for-js#678] opened 2017-12-12 13:38 UTC
Hi there,

We have a problem with the `aquireTokenRedirect` method. We have setup our code to try to silently obtain an access token with `aquireToken` and if that fails, retry using the `aquireTokenRedirect` method as demonstrated [here](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca/blob/master/TodoListSPA/app.js#L110).

### What we expect

We have recently added PowerBI permissions to our application in AAD. We expected silent token acquisition to fail, to then be redirected to the login screen and then a consent screen, allowing the user to grant permission.

### What we get

Instead we get an error page `AADSTS90023: Unsupported 'prompt' value.`

<img width="1146" alt="screen shot 2017-12-12 at 13 16 50" src="https://user-images.githubusercontent.com/4233139/33886520-c143894c-df3e-11e7-8490-b353d66fd945.png">

### Details

We found that the `prompt` query parameter was set to `select_account` and [upon inspection of the code](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L806), we found this was always true. This has been the case [since the method was introduced](https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/811aea1a16871d01742fffa7f161933251e53f03#diff-e8498bc0c6f6194579104b92f29a2ab3R643). We also found that if we simply removed the `prompt` query parameter, we were redirected successfully to login and consent.

When we dug into why the silent access token acquisition was failing, we found we were getting an MFA error `AADSTS50079: The user is required to use multi-factor authentication.` We believe that the setting the prompt to `select_account` incorrectly constrains the interactive flow for a single use case where the user is not logged in.

### Changes

As we see it, there are a couple of options;

1. Remove prompt parameter from the navigate url in popup and redirect methods.
2. Allow library consumers to pass the prompt value in to the popup and redirect methods.

Where we need some guidance is why `select_account` was used in the first place when ommitting the prompt parameter altogether seems to be more robust? We don't have a good understanding of the possible prompt values, nor do we know all possible login flows. Hopefully we can get some clarification on this. 

Cheers! Ryan.

**Comment by rohitnarula7176** [comment] 2017-12-13 23:58
@RaniSputnik The above error is thrown when you call acquireTokenRedirect method by supplying 'prompt=select_account' as extraQueryParameters which adds to the prompt ='select_account' hard coded in the method leading to multiple prompt values and hence the error. prompt value should not be altered by the user as per the library design. Can you explain the reason why you need to pass prompt = consent in your application.
To answer your question regarding prompt values. There are 3 types of prompt values allowed -  none, consent, select_account and below is their expected behavior.
1. none - The authorization server does not display any authentication or user consent screens; it will return an error if the user is not already authenticated and has not pre-configured consent for the requested resources. This cannot be used for acquireTokenRedirect as the user needs to see the authentication screen to enter their credentials or to grant access.
2. consent. Having this value will lead to an additional consent screen which will ask you to grant permission to access resources in your organization that only an admin can grant in some cases.
3. select_account - The authorization server prompts the user to select a user account. This allows a user who has multiple accounts at the authorization server to select amongst the multiple accounts that they may have current sessions for. This is the preferred value and hence it is hard coded in adal's code. 

Please let me know if you have additional questions/concerns.

**Comment by RaniSputnik** [comment] 2017-12-21 09:31
Hi Rohit, thanks for the explaination.

In our case we were not passing a prompt value to the `extraQueryParameters` argument, we used the method as follows;
```
authContext.aquireTokenRedirect(powerBiResource, '&scope=Dashboard.Read.All', null);
```
We also captured the network activity and confirmed that only a single prompt parameter was being used when redirecting. I have to omit some details, but here is the structure of the redirect that was performed;
```
https://login.microsoftonline.com/XXX/oauth2/authorize?
    response_type=token&client_id=XXX&
    resource=https://analysis.windows.net/powerbi/api&
    redirect_uri=XXX&state=XXX&nux=1&
    domain_hint=XXX&client-request-id=XXX&
    x-client-SKU=Js&x-client-Ver=1.0.15&
    prompt=select_account%26scope%3DDashboard.Read.All&
    login_hint=XXX
```
I tried changing this URL to remove some of the encoding and now it works correctly;
```
https://login.microsoftonline.com/XXX/oauth2/authorize?
    response_type=token&client_id=XXX&
    resource=https://analysis.windows.net/powerbi/api&
    redirect_uri=XXX&state=XXX&nux=1&
    domain_hint=XXX&client-request-id=XXX&
    x-client-SKU=Js&x-client-Ver=1.0.15&
    prompt=select_account&scope=Dashboard.Read.All&
    login_hint=XXX
```
It seems that the URL encoding is messing things up, when I took another look at the code I found [this section](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L777);
```
if (extraQueryParameters) {
            urlNavigate += encodeURIComponent(extraQueryParameters);
}
```
Perhaps the URI encoding should be removed from this step? The browser will do this when the location is changed. Let me know your thoughts.

**Comment by rohitnarula7176** [comment] 2017-12-21 19:47
@RaniSputnik Thank you for pointing out this issue. I have made a fix for this in the dev branch. Can you please test it and confirm if it resolves your issue. We wont be able to release a official version of it until Jan due to the holidays.

**Closed** 2017-12-21 21:43 UTC
Labels: 2 - Done
