### ISSUE TITLE
Infinite loop using Safari on OS X

### ISSUE THREAD

**Issue by MMM300** [AzureAD/azure-activedirectory-library-for-js#451] opened 2016-11-28 16:35 UTC
We have an application that runs perfectly in Firefox and Chrome but goes into an infinite loop with both Safari & iCab on OS X. 

It seems that WebKit browsers on OS X has this behaviour.

Adal JS Version: 1.0.13
UI-Router: 0.3.1
Angular: 1.5.8

Safari: 9, 10

No suggested solution mentioned in the FAQ helps. 

Logs from the first callback after successful login at the ADFS login page:

**Firefox**

```
[Info] $rootScope.userInfo: {"isAuthenticated":false,"userName":"","loginError":""}
[Info] Tue, 29 Nov 2016 07:31:13 GMT:1.0.13-VERBOSE: Location change event from https://localhost:8443/login/#/id_token=<token>&state=<state> to https://localhost:8443/login/#/id_token=<token>&state=<state>
[Info] GET HASH (_getHash): "#/id_token=<token>"
[Info] GET REQUEST INFO (getRequestInfo): "#/id_token=<token>"
[Info] Tue, 29 Nov 2016 07:31:13 GMT:1.0.13-VERBOSE: State: <state>
[Info] Tue, 29 Nov 2016 07:31:13 GMT:1.0.13-INFO: State status:true; Request type:LOGIN
[Info] Tue, 29 Nov 2016 07:31:13 GMT:1.0.13-INFO: State is right
```

**Safari**

```
[Info] $rootScope.userInfo: {"isAuthenticated":false,"userName":"","loginError":""}
[Info] Tue, 29 Nov 2016 07:36:42 GMT:1.0.13-VERBOSE: Location change event from https://localhost:8443/login/ to https://localhost:8443/login/ 
[Info] GET HASH (_getHash): "" 
[Info] Tue, 29 Nov 2016 07:36:42 GMT:1.0.13-VERBOSE: Url: partial/navigation/topnav.html maps to resource: <group>
[Info] ACQUIRE TOKEN (acquireToken) callback: undefined
[Info] Tue, 29 Nov 2016 07:36:42 GMT:1.0.13-WARNING: User login is required 
[Warning] Received acquireTokenFailure from Adal. 
```

This might be due to the many 302 redirects that ADFS performs on login to set cookies.
The cookies MSISAuth and MSISAuthenticated are not set in Safari.

**Comment by tushargupta51** [comment] 2016-12-05 21:45
@MMM300 The logs seems to be for 2 different calls. The Safari log is for an acquireToken call instead of login. Since there is no logged in user, acquireToken call fails with the error: "User login is required". Can you share the Safari logs that shows the loop as well.

**Comment by MMM300** [comment] 2016-12-06 07:01
```
[Info] {"isAuthenticated":false,"userName":"","loginError":null} 
[Info] Location change event from https://localhost:8443/login/ to https://localhost:8443/login/ 
[Info] Url: partial/navigation/topnav.html maps to resource: <value> 
[Info] User login is required 
[Warning] Received acquireTokenFailure from Adal. 
[Info] Expected state: 6643cfeb-ab8c-4b54-9cac-699c5857f6c0 startPage:https://localhost:8443/login/ 
[Info] Navigate url:<ADFS>/oauth2/authorize?response_type=id_token&client_id=<value>&redirect_uri=https%3A%2F%2Flocalhost%3A8443%2Flogin&state=<value>&nux=1&client-request-id=<id>&x-client-SKU=Js&x-client-Ver=1.0.13 
[Info] Navigate to:<ADFS>/oauth2/authorize?response_type=id_token&client_id=<value>&redirect_uri=https%3A%2F%2Flocalhost%3A8443%2Flogin&state=<value>&nux=1&client-request-id=<id>&x-client-SKU=Js&x-client-Ver=1.0.13&nonce=<value> 
[Info] Error when acquiring token for resource: <name> 
stack:
undefined
[Info] Url: partial/alerts/alerts.html maps to resource: <value> 
[Info] login is in progress. 
[Info] Url: partial/errors/errors.html maps to resource: <value> 
[Info] login is in progress. 
[Info] Url: partial/navigation/footer.html maps to resource: <value> 
[Info] login is in progress. 
[Info] Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[],"cache":{},"url":"partial/alerts/alerts.html","headers":{"Accept":"application/json, text/plain, */*"},"data":"login in progress, cancelling the request for partial/alerts/alerts.html"} 
[Info] Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[],"cache":{},"url":"partial/errors/errors.html","headers":{"Accept":"application/json, text/plain, */*"},"data":"login in progress, cancelling the request for partial/errors/errors.html"} 
[Info] Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[],"cache":{},"url":"partial/navigation/footer.html","headers":{"Accept":"application/json, text/plain, */*"},"data":"login in progress, cancelling the request for partial/navigation/footer.html"} 
[Info] Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[],"cache":{},"url":"partial/navigation/topnav.html","headers":{"Accept":"application/json, text/plain, */*"},"data":"User login is required|login required|undefined"} 
[Info] Location change event from https://localhost:8443/login/ to https://localhost:8443/login/#/ 
[Info] Url: partial/open/open.html maps to resource: <value> 
[Info] login is in progress. 
[Info] Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[null],"cache":{},"headers":{"Accept":"text/html"},"url":"partial/open/open.html","data":"login in progress, cancelling the request for partial/open/open.html"} 
[Info] State change error occured. Error: {"method":"GET","transformRequest":[null],"transformResponse":[null],"cache":{},"headers":{"Accept":"text/html"},"url":"partial/open/open.html","data":"login in progress, cancelling the request for partial/open/open.html"} 
[Info] Setting defaultPrevented to true if state change error occured because adal rejected a request. Error: login in progress, cancelling the request for partial/open/open.html 

Loop restart 
[Info] {"isAuthenticated":false,"userName":"","loginError":""} 
[Info] Location change event from https://localhost:8443/login/ to https://localhost:8443/login/ 
[Info] Url: partial/navigation/topnav.html maps to resource: <value> 
[Info] User login is required 
...
```

**Comment by MMM300** [comment] 2016-12-07 11:38
I updated the first comment. The redirect contains the id_token value for Safari but no cookies from the ADFS.

Redirect format:
https://localhost:8443/login#id_token=<token value>&state=<hash>

**Comment by tushargupta51** [comment] 2017-01-11 18:19
@MMM300 I wonder why you get the "User login is required" error after a successful login. For some reason, adal cannot find the id_token in browser storage and that's why another login is initiated. Can you check if the local storage has the tokens after login? Fiddler trace will help more here since we need to find out what gets passed in the request and what is returned in the response.

**Comment by MMM300** [comment] 2017-01-12 12:39
### Callback URL (after login)

`https://localhost:8443/login#id_token=<Token 836 bytes>&state=<State 36 bytes>`

### ADFS REQUEST
```
CONNECT <ADFS DOMAIN>:443 HTTP/1.1
Host: <ADFS DOMAIN>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12
Connection: keep-alive
Connection: keep-alive

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.3 (TLS/1.2)

Random: 58 77 68 B6 7B 30 43 BF AD 52 DD DE 5D 03 21 B3 EB DF 87 3E 98 97 93 B1 26 F5 EE 1E 1A EC 7B 22

"Time": 2066-12-23 04:13:28
SessionID: empty
Extensions: 
	server_name	<ADFS DOMAIN>	
elliptic_curves	secp256r1 [0x17], secp384r1 [0x18], secp521r1 [0x19]
	
ec_point_formats	uncompressed [0x0]
	
signature_algs	sha256_rsa, sha1_rsa, sha384_rsa, sha512_rsa, sha256_ecdsa, sha1_ecdsa, sha384_ecdsa, sha512_ecdsa
	
NextProtocolNego	empty
	
ALPN		http/1.1, http/1.0
	
status_request	OCSP - Implicit Responder
	
SignedCertTimestamp (RFC6962)	empty
	e
xtended_master_secret	empty
Ciphers: 
	[00FF]	TLS_EMPTY_RENEGOTIATION_INFO_SCSV
	[C02C]	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
	[C02B]	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
	[C024]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
	[C023]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
	[C00A]	TLS1_CK_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
	[C009]	TLS1_CK_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
	[C030]	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	[C02F]	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	[C028]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
	[C027]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
	[C014]	TLS1_CK_ECDHE_RSA_WITH_AES_256_CBC_SHA
	[C013]	TLS1_CK_ECDHE_RSA_WITH_AES_128_CBC_SHA
	[009D]	TLS_RSA_WITH_AES_256_GCM_SHA384
	[009C]	TLS_RSA_WITH_AES_128_GCM_SHA256
	[003D]	TLS_RSA_WITH_AES_256_CBC_SHA256
	[003C]	TLS_RSA_WITH_AES_128_CBC_SHA256
	[0035]	TLS_RSA_AES_256_SHA
	[002F]	TLS_RSA_AES_128_SHA

Compression: 
	[00]	NO_COMPRESSION

```

### ADFS RESPONSE
```
HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 12:29:58.345
Connection: close
EndTime: 12:31:29.001
ClientToServerBytes: 10578
ServerToClientBytes: 10670

A SSLv3-compatible ServerHello handshake was found. Fiddler extracted the parameters below.

Version: 3.3 (TLS/1.2)
SessionID:	24 0B 00 00 1B 75 2C 73 D2 AA C5 81 54 80 E6 88 18 B3 55 5F 2B C3 C6 B1 A4 12 62 43 07 5B D4 CE
Random:		58 77 68 B6 14 05 75 C3 59 74 93 04 29 1D F1 0D 2D DC A1 D2 B2 F9 FC 3D D1 F8 E9 BE D2 53 C6 D1
Cipher:		TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 [0xC030]
CompressionSuite:	NO_COMPRESSION [0x00]
Extensions:
		extended_master_secret	empty
		renegotiation_info	00
		server_name	empty



```

### Safari

Cookies: None  

_As mentioned above Firefox has 3 cookies at this stage: MSISAuth, MSISAuthenticated, MSISLoopDetectionCookie_

Local storage: empty

Session storage: empty


This is the state exactly before the Safari tries to connect back to the Adal JS application.

**Comment by abettadapur** [comment] 2017-04-21 22:22
I am also seeing this issue using ADAL V1.0.14. Is there any timeline for its resolution

**Comment by neelDev** [comment] 2017-05-03 04:59
@tushargupta51 

I am also facing same issue while using Safari browser. In other browsers ADAL login is working as expected.

Any updates on the above issue.

**Comment by rohitnarula7176** [comment] 2017-06-14 00:34
@neelDev @abettadapur  If cookies are blocked by the browser, there is nothing the library can do to resolve it. The library relies on cookies and storage to login and acquire token for a resource. From the above trace, I can see the cookies are none and the storage is empty. Closing this issue.

**Closed by rohitnarula7176** 2017-06-14 00:34 UTC
Labels: Investigating, User Reported

**Comment by Vivihung** [comment] 2017-08-17 05:50
@rohitnarula7176 
I'm also investigating infinite AAD login loop for iPhone safari browser in private mode.

Just try to understand more about this library.
When we use localstorage mode, can adal.js be functional even cookie is blocked by browser?
or 
No matter in what mode, adal.js cannot work without cookie enable

What's the critical browser dependency for adal.js?

**Comment by ramesh-chandra** [comment] 2018-01-22 21:28
Although the issue is Closed. But few users of my site are still facing the same problem in Safari desktop/mobile. 
Adal JS Version: 1.0.15
Angular: 1.5.8

Let me know if anyone resolved this issue.

**Comment by MarkHerhold** [comment] 2018-06-25 12:30
I encountered the same issue on Safari. The fix in my case was to ensure that the redirect URI ends with a `/`.

This issue describes the same problem. https://github.com/IdentityModel/oidc-client-js/issues/238#issuecomment-271105795
