### ISSUE TITLE
Token Renewal Failed | Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by balajimadgundi** [AzureAD/azure-activedirectory-library-for-js#578] opened 2017-06-22 21:15 UTC
I am using the Adal 1.14.0 version and sessionStorage. Below is App init:
adalProvider.init({
                tenant: Dependencies.Tenant,
                clientId: Dependencies.ClientId,
                endpoints: Dependencies.Endpoints,
                postLogoutRedirectUri: Dependencies.ClientGatewayLogoutUrl
            }, $httpProvider);

I am getting the "Token renewal operation failed due to timeout" issue when trying to open the application in new Tab/window of IE browser(IE 11) for subsequent login.

When I am logging in first time(first tab) it works. For subsequent login in new Tab/Window in IE, I am getting this "Token renewal operation failed due to timeout" from AcquireToken:Failure event.

I have checked this on other users machines(4-5), The same scenario is working fine on other machine's IE browser. Does not work only in my machine's IE subsequent login scenario.

I have already verified all my IE settings, they are same as of other user's IE settings where it is working. I need to know if this is causing due to any IE settings or anything else. I can not rollout the code just because it is working in 3-4 machines since it is failing in my machine and other application user base might have same IE settings as mine(if this is causing due to IE settings).

PFA logs
[SessionStorageIssueLogs.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1096199/SessionStorageIssueLogs.txt)

**Comment by rohitnarula7176** [comment] 2017-06-22 23:23
@balajimadgundi Can you share a working demo of your code so I can debug this further. Also can you please attach the fiddler trace for this issue so I can confirm that you actually receive a token from AAD.

**Comment by thdotnet** [comment] 2017-06-28 03:38
I was facing the same problem. Here's how I've solved it:

    /**
     * Gets token for the specified resource from the cache.
     * @param {string}   resource A URI that identifies the resource for which the token is requested.
     * @returns {string} token if if it exists and not expired, otherwise null.
     */
    AuthenticationContext.prototype.getCachedToken = function (resource) {
        if (!this._hasResource(resource)) {
            return null;
        }

        var token = this._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource);
        var expiry = this._getItem(this.CONSTANTS.STORAGE.EXPIRATION_KEY + resource);

        // If expiration is within offset, it will force renew
        var offset = this.config.expireOffsetSeconds || 300;

        if (expiry && (expiry > this._now() + offset)) {
            return token;
        } else {
            this._saveItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource, '');
            this._saveItem(this.CONSTANTS.STORAGE.EXPIRATION_KEY + resource, 0);
            //new line included
            localStorage.clear();
            sessionStorage.clear();

            return null;
        }
    };

**Comment by thdotnet** [comment] 2017-06-30 00:11
@balajimadgundi can you test with my solution? I was able to solve the issue...

**Comment by ashishtechie** [comment] 2017-07-28 22:02
Hey is there any update on this. I suppose this is more of Angular 2.X plus issue and you are right it happens for some time in my browser too but then after it have a session or something it stops happening. Are we getting a native support for Angular 2.x plus?

**Comment by jmprieur** [comment] 2017-07-29 18:01
It's on the backlog, but no ETA yet.

Meanwhile, we've released a new version of ADAL.js (ADAL.js 1.015) adding acquireTokenPopup and acquireTokenRedirect, and supporting claims challenges (when a service requires more from the user, for instance Multi factor authentication). You might want to look at the plain JavaScript here: https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/tree/master/TodoListSPA and adapt it to angular v2?

**Comment by jmprieur** [comment] 2017-09-03 20:27
Duplicate of #600

**Closed by jmprieur** 2017-09-03 20:27 UTC
