### ISSUE TITLE
Firefox first loading error

### ISSUE THREAD

**Issue by NDalvise** [AzureAD/azure-activedirectory-library-for-js#567] opened 2017-06-06 08:44 UTC
I have my project based on AngularJS 1.5.8, ASP.NET and I use ADAL.js 1.0.14...
I'm using this workaround ([https://gist.github.com/tushargupta51/78ce0b6bce998f6851abd02d91eb3a95](https://gist.github.com/tushargupta51/78ce0b6bce998f6851abd02d91eb3a95)) as suggested here [https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q1-my-app-is-re-loading-every-time-adal-renews-a-token](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q1-my-app-is-re-loading-every-time-adal-renews-a-token).
Well, my code compile and works well on Chrome (58.0.3029.110 64-bit) and Edge but i have issues with Mozilla Firefox (53.0.3 64 bit) :
- webapp loads
- i authenticate in Azure
- page loads as in screenshot
- errors in console log and the ng-view (the corps of the page) is blank

If then I refresh the page everything works as it should.

Any suggestions?

![errore iniziale foxwin app 2](https://cloud.githubusercontent.com/assets/29203499/26820951/fc2d3c94-4aa4-11e7-8566-45ff059e9068.PNG)

**Comment by rohitnarula7176** [comment] 2017-06-12 17:29
@NDalvise Can you share a working demo of your code so I can investigate this further.

**Comment by rohitnarula7176** [comment] 2017-06-12 21:59
@NDalvise The issue is fixed in the dev branch. We will release a new version of adal 1.0.15 by end of this week and it will have a fix for this issue.

**Comment by rohitnarula7176** [comment] 2017-06-14 20:19
Fixed in dev

**Closed by rohitnarula7176** 2017-06-14 20:19 UTC
Labels: Needs Info
