### ISSUE TITLE
iframe should be removed after renew token have been retrieved

### ISSUE THREAD

**Issue by Hagsten** [AzureAD/azure-activedirectory-library-for-js#199] opened 2015-12-14 08:41 UTC
I am using ADAL to authenticate to cross domain APIs.

When ADAL tries to renew the token it uses a hidden iframe, when the token is retrieved, this iframe remains on the webpage and will in turn load my website all over again which causes the same scripts to be run again (since the return url from the authentication is my root page which is the same as the one initiating the authentication). I can clearly see this behaviour if I remove the code that hides the iframe.

For now I have 2 APIs for which I am authenticating with, which will cause ADAL to create 2 iframes. These iframes and my main browser will together fire 12 calls (OPTION and GET) towards the first enpoint and 8 calls (OPTION and GET) towards the second enpoint (which is dependant on the result of the first). The expected behaviour is 2 (OPTION + GET) for the first endpoint and 2 (OPTION + GET) for the second. If I remove the iframes when the token is retireved I get the expected behaviour.

I believe that the iframes should be removed once their purpose is fulfilled and then re-created whenever they are needed. This will avoid that the website is reloaded inception-style.

A final thought, maybe I am using ADAL incorrectly? I am initializing ADAL at config-time (with my 2 endpoints) and then I am logging in if the userInfo is not authenticated when the ui-router state changes (which will ensure that the user always is authenticated).

```javascript
if (adal.userInfo && adal.userInfo.isAuthenticated) {
    $rootScope.loggedIn = true;
} else {
    if (adal.loginInProgress()) {
        console.log('Waiting for login to complete, exiting...');
        return;
    }

    console.log('logging in...');
    $rootScope.loggedIn = false;
    adal.login();
}
```

This might relate to https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/151

**Comment by drGarbinsky** [comment] 2015-12-16 02:31
I think I will take a crack at trying this approach to see if it fixes the reload issue. What you're describing matches my symptoms quite closely.

**Comment by tushargupta51** [comment] 2016-03-18 03:38
@Hagsten can you provide logs for your issue? You can add this to your app.js:
````
Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    }
};
````

**Comment by tushargupta51** [comment] 2016-05-18 22:11
Closing this as dup of #151. Both issues root caused to the same bug: app loading in iframe after token is renewed.

**Closed by tushargupta51** 2016-05-18 22:11 UTC
Labels: Needs Investigation, P2
