### ISSUE TITLE
Improve error handling on acquireToken function

### ISSUE THREAD

**Issue by andreesteve** [AzureAD/azure-activedirectory-library-for-js#107] opened 2015-04-09 00:34 UTC
Calling acquireToken takes a callback function that returns the token or an error message.
The acquireToken method uses an iframe to send the requests to the AAD service.

When AAD service fails, the acquireToken never calls the callback with an error code, which leaves the application waiting for ever on the library result.

The scenario that I found that makes the library to not return errors, even though they happen, is when the iframe does not send cookies or send old cookies to the AAD service.

I am afraid that other error scenarios might make the library never return as well.

**Comment by omercs** [comment] 2015-04-13 23:21
Is this happening with angular usage?

**Comment by andreesteve** [comment] 2015-04-18 07:06
No, we are using the adal.js directly, without the angular wrapper.

**Comment by weijjia** [comment] 2015-05-15 00:09
can you provide the fiddler trace? I couldn't reproduce it anyway.

**Comment by RobARichardson** [comment] 2015-06-10 22:01
+1.  I'm using adal.js w/ Angular and I believe I'm having the same issue.  To reproduce, I launch my app, sign-in, open my app in a second browser window/tab, sign-out from within that second tab/window (adalAuthenticationService.logOut()), and then go back to the other tab and do anything that issues an XHR to a protected resource.  At that point, my app hangs - can't do anything.  After inserting various console statements into the ProtectedResourceInterceptor, I can see that the call to authService.acquireToken() never completes with a success or failure.

**Comment by tushargupta51** [comment] 2016-05-16 21:44
Apologies for the delay.

@andreesteve This issue is fixed now in 1.0.10, earlier angular was not calling the registered callback if AAD returns an error in the response. Please give it a shot.

@RobARichardson  If you sign out from second tab, then adal will clear all the browser storage and the aad cookie will be removed. So, when you do anything in first tab, it does not find a token in the storage and acquireToken method does not send a request to AAD because user is not logged in. If you turn on logging (instructions in README.md), that might give some more info about what's happening. Let us know if you are still running into this issue.

**Closed** 2016-05-16 21:44 UTC
Labels: bug
