### ISSUE TITLE
Log out doesn't work

### ISSUE THREAD

**Issue by ESadouski** [AzureAD/azure-activedirectory-library-for-js#811] opened 2018-10-03 13:12 UTC
**Issue type**
  bug report

**Issue description:**
Log out doesn't work for Guest users, but it works for Members. 
Adal library v1.0.17

**Steps to reproduce:**
1. Login to the app with Guest user type
2. Logout

**Current behavior:**
After logout, you redirect to 
> https://login.microsoftonline.com/***/oauth2/logout?post_logout_redirect_uri=***

but then there is no redirect to the post_logout_redirect_uri

**Expected behavior:**
After logout, you redirect to 
> https://login.microsoftonline.com/***/oauth2/logout?post_logout_redirect_uri=***

and then there is should be redirect to the post_logout_redirect_uri

**Comment by benjaminao** [comment] 2018-10-05 14:05
Hi, I have the same issue, can you help me with that, this is my Adal Configuration:

{
tenant: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
clientId: clientId,
redirectUri: window.location.origin + '/#/home',
postLogoutRedirectUri: window.location.origin + '/#/login',
logOutUri: window.location.origin + '/#/login',
extraQueryParameter: 'prompt=select_account'
}

When I call the logout() method go to a screen with this message
"You signed out of your account
It's a good idea to close all browser windows."
and no redirect to my **postLogoutRedirectUri** also when close and try to log in the user still signed in.
But when I login with a member account work perfect. 
Please help me with that, currently I have a app in production with this problem

**Comment by benjaminao** [comment] 2018-10-05 19:19
Hi, I have the same issue, can you help me with that, this is my 
**Adal Configuration:**
{
tenant: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
clientId: clientId,
redirectUri: window.location.origin + '/#/home',
postLogoutRedirectUri: window.location.origin + '/#/login',
extraQueryParameter: 'prompt=select_account'
}

When I call the **logout()** method go to a screen with this message
"You signed out of your account
It's a good idea to close all browser windows."
and no redirect to my **postLogoutRedirectUri** also when close and try to log in the user still signed in.
But when I login with a member account work perfect.
Please help me with that, currently I have a app in production with this problem

**Comment by nehaagrawal** [comment] 2018-10-16 20:09
@ESadouski  can you please paste your adal configuration here?

**Comment by benjaminao** [comment] 2018-10-16 20:13
public get getAdalConfig(): any {
    let clientId = this.appConfig.getConfig('adalClient');
    let apiUrl = this.appConfig.getConfig('api');

    return {
      tenant: 'XXXXXXXXXXXXXXXXXXXXXXXX',
      clientId: clientId,
      redirectUri: window.location.origin + '/#/home',
      postLogoutRedirectUri: window.location.origin + '/#/login',
      extraQueryParameter: 'prompt=select_account'
    };

**Comment by nehaagrawal** [comment] 2018-10-17 17:40
@ESadouski @benjaminao  we are working on this issue and I will let you know once I have fix. Thank you for your patience.

**Comment by nehaagrawal** [comment] 2018-10-18 19:40
@ESadouski @benjaminao  can you please add the post_logout_redirect_uri as the logout_url on the app registration portal and try again?

**Comment by nehaagrawal** [comment] 2018-10-22 18:32
@ESadouski @benjaminao  Can you please confirm if it works after adding post_logout_redirect_uri as the logout_url on the app registration portal

**Comment by benjaminao** [comment] 2018-10-22 18:36
Hi, @nehaagrawal, thanks for taking the time to help us, I did it and it does not work.

**Comment by nehaagrawal** [comment] 2018-10-23 18:59
@benjaminao  can you please try one more thing? Can you please make sure that logout_uri is also registered in the Reply URLs on the app registration portal?

**Comment by nehaagrawal** [comment] 2018-10-25 21:26
@benjaminao I wasn't able to reproduce this issue in adal. I was able to reproduce in msal though.  Is it possible for you to send a fiddler for this issue?

**Comment by benjaminao** [comment] 2018-10-25 23:31
@nehaagrawal The problem is with Guest users! If the user is a member of the azure account work fine! But if the user is not a member the logout doesn’t work

**Comment by ESadouski** [comment] 2018-10-31 16:11
Hi @nehaagrawal, 
I also tried post_logout_redirect_uri, but unfortunately, it's still not working. Any news from your side?

**Comment by benjaminao** [comment] 2018-11-13 19:35
Hi **@nehaagrawal**, Any news about this problem? My company is considering a change to another logging provider because the app cant does not wait for more for this solution. May you help me with this, please!

**Comment by benjaminao** [comment] 2018-11-26 17:59
@nehaagrawal The problem is with Guest users! If the user is a member of the azure account work fine! But if the user is not a member the logout doesn’t work. Any news from your side?

**Comment by benjaminao** [comment] 2018-12-03 14:27
Hi @ESadouski, did you fix the problem?

**Comment by ESadouski** [comment] 2018-12-03 19:27
Hi @benjaminao unfortunately not, The problem still exists.

**Comment by benjaminao** [comment] 2018-12-10 15:16
@ESadouski Hi, can you check why when you try to logout() don't still sing in and not redirect?

this is my package.json 

"dependencies": {
    "@agm/core": "1.0.0-beta.1",
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.0-RC.0",
    "@angular/compiler": "4.4.0-RC.0",
    "@angular/core": "4.4.0-RC.0",
    "@angular/forms": "4.4.0-RC.0",
    "@angular/http": "4.4.0-RC.0",
    "@angular/platform-browser": "4.4.0-RC.0",
    "@angular/platform-browser-dynamic": "4.4.0-RC.0",
    "@angular/router": "4.4.0-RC.0",
    "@types/googlemaps": "3.30.1",
    "@types/moment": "2.13.0",
    "adal-angular": "1.0.16",
    "angulartics2": "^4.6.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "expose-loader": "0.7.4",
    "file-saver": "^1.3.8",
    "font-awesome": "4.7.0",
    "moment": "2.19.1",
    "ng2-toastr": "4.1.2",
    "primeng": "4.3.0",
    "rxjs": "5.5.11",
    "ts-helpers": "1.1.1",
    "web-animations-js": "^2.3.1",
    "zone.js": "0.8.17"
  },

my adal config is 
      tenant: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
      clientId: clientId,
      isAngular: true,
      redirectUri: window.location.origin + '/#/home',
      postLogoutRedirectUri: window.location.origin + '/#/login',
      extraQueryParameter: 'prompt=select_account'

in the node_module/adal-angular/lib/adal.js
 
AuthenticationContext.prototype.logOut = function () {
        this.clearCache(); //<<<<<<<<<<<<<<<< this line look like no clear the cache 
        this._user = null;
        var urlNavigate;

        if (this.config.logOutUri) {
            urlNavigate = this.config.logOutUri;
        } else {
            var tenant = 'common';
            var logout = '';

            if (this.config.tenant) {
                tenant = this.config.tenant;
            }

            if (this.config.postLogoutRedirectUri) { 
           //<<<<<<<<<<<<<<<< affter logout don't work also no redirect according my configuration
                logout = 'post_logout_redirect_uri=' + encodeURIComponent(this.config.postLogoutRedirectUri);
            }

            urlNavigate = this.instance + tenant + '/oauth2/logout?' + logout;
        }

        this.info('Logout navigate to: ' + urlNavigate);
        this.promptUser(urlNavigate);
    };

**Comment by benjaminao** [comment] 2018-12-10 15:18
<img width="1164" alt="buil-363-screenshot" src="https://user-images.githubusercontent.com/14250305/49741639-d6794100-fc64-11e8-85e1-4f169169f05a.png">

**Comment by benjaminao** [comment] 2018-12-10 15:18
![screen shot 2018-12-10 at 10 17 21 am](https://user-images.githubusercontent.com/14250305/49741690-f446a600-fc64-11e8-87fa-b994168591a8.png)

**Comment by benjaminao** [comment] 2018-12-10 15:19
![screen shot 2018-12-10 at 10 19 24 am](https://user-images.githubusercontent.com/14250305/49741743-16d8bf00-fc65-11e8-9c57-b36ded9308af.png)

**Comment by benjaminao** [comment] 2018-12-10 15:20
![screen shot 2018-12-10 at 10 20 20 am](https://user-images.githubusercontent.com/14250305/49741825-3a9c0500-fc65-11e8-9298-042bef93d4cd.png)

**Comment by benjaminao** [comment] 2018-12-10 15:22
![screen shot 2018-12-10 at 10 20 20 am](https://user-images.githubusercontent.com/14250305/49741887-69b27680-fc65-11e8-8888-a9f9bfccf5be.png)

**Comment by benjaminao** [comment] 2018-12-10 15:24
In the adal.js

![screen shot 2018-12-10 at 10 22 34 am](https://user-images.githubusercontent.com/14250305/49742085-c6159600-fc65-11e8-91b9-d7825e5d816d.png)

**Comment by benjaminao** [comment] 2018-12-10 15:29
When I try to login the user still signed in

![screen shot 2018-12-10 at 10 25 54 am](https://user-images.githubusercontent.com/14250305/49742401-797e8a80-fc66-11e8-8056-0c10708626ca.png)

**Comment by benjaminao** [comment] 2018-12-10 15:32
Please let me know if need more information about it! The adal.js have this issue!! 
@nehaagrawal The problem is with Guest users! If the user is a member of the azure account work fine! But if the user is not a member the logout doesn’t work

**Comment by benjaminao** [comment] 2018-12-10 16:46
I try using this add id_token_hint to logout url #677 and the redirect work perfect but when try to login  the the user still signed in 

![screen shot 2018-12-10 at 10 25 54 am](https://user-images.githubusercontent.com/14250305/49747306-26f69b80-fc71-11e8-8a72-228b59046c6f.png)

**Comment by StuntThumper88** [comment] 2019-02-25 17:14
Was this resolved? Im having this issue too

**Comment by benjaminao** [comment] 2019-02-25 17:19
@StuntThumper88 
No, I still waiting for a solution!

**Comment by JACrazy** [comment] 2019-02-26 16:52
noticing this issue too

**Comment by aarshad786** [comment] 2019-03-20 04:24
@benjaminao... you should be using logOut() and not logout() according to adal documentation

**Comment by mokutsu** [comment] 2019-03-23 15:58
hey we're also noticing similar issues

**Comment by kameelyan** [comment] 2019-04-25 13:26
Having a similar issue as well. Looking at the network tab:

Request URL: https://login.microsoftonline.com/KTGLBUC.onmicrosoft.com/oauth2/logout?post_logout_redirect_uri=<url hidden for privacy reasons>

The next request is:
Request URL: https://login.live.com/logout.srf?id=12&ru=https%3a%2f%2flogin.microsoftonline.com%2fktglbuc.onmicrosoft.com%2foauth2%2flogoutredirect

And finally the user is stopped at this page:
Request URL: https://login.microsoftonline.com/ktglbuc.onmicrosoft.com/oauth2/logoutredirect?lc=1033

**Comment by Lukbrayn123** [comment] 2019-05-13 05:54
Facing logout problem in adal-angular v1.0.17. 
I am logged in with one user, then duplicate a tab and logged out the user and in this tab logged in with different user. 
When going to the previous user and refresh page user does not log in with the new user, old user can able to perform actions. I am using session storage to store token.
This is not accepted, If the user logged out, then it should be logged out from all tabs. The session should be updated with the latest data.

**Comment by PraveenVerma17** [comment] 2019-06-14 09:24
Did anyone get the fix for this issue. We are also facing the similar issue.

**Comment by raviji** [comment] 2019-07-18 13:37
am also facing this issue in my application and waiting for the solution

**Comment by slomangino123** [comment] 2019-07-27 21:22
I am seeing the exact issue above using angular-msal wrapper that @benjaminao stated. My user is still signed in after first logout action. If i log in again with that user, it states that the user is still logged in. If i log out a second time, the user is successfully logged out and the redirect works as expected. Still waiting for a solution.

**Comment by dimaatkaev** [comment] 2019-09-20 08:33
Hello @nehaagrawal, do you have any updated with this issue?

**Comment by sameerag** [comment] 2019-09-20 16:11
@dimaatkaev Is this seen with ADAL JS or MSAL JS? Also can you please share the version of the library used? I do think latest MSAL JS (core and not angular) does not have this issue.

**Comment by dimaatkaev** [comment] 2019-09-23 08:22
@sameerag I believe this is an issue of the platform, not the lib, I'm using self-written lib

**Comment by sameerag** [comment] 2019-09-23 15:27
@dimaatkaev I can open a service ticket to the STS team provided I have a faithful repro. Can you please share the steps?

**Comment by dimaatkaev** [comment] 2019-10-01 15:33
@sameerag, sorry for the later answer
you can use the steps provided by @ESadouski in the initial issue:
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/811#issue-366332243

**Comment by abhilashrainchu** [comment] 2019-11-06 19:41
@kameelyan  i am also facing a similar issue, Does the issue got resolved ?

**Comment by kameelyan** [comment] 2019-11-12 14:06
Sorry @abhilashrainchu, it was not.

**Comment by jmckennon** [comment] 2019-12-12 23:37
@sameerag was this fixed with the release of `msal@1.2.0`?

**Comment by yesoreyeram** [comment] 2019-12-18 17:20
@sameerag was this fixed? Anyone have workaround?

**Comment by dalaoque** [comment] 2020-03-30 13:02
I have the same problem. Is there a solution?

**Comment by dalaoque** [comment] 2020-03-30 13:32
Ok, I solved it!

**Comment by kameelyan** [comment] 2020-03-30 13:33
Care to share your solution @dalaoque ?

**Comment by abhilashrainchu** [comment] 2020-03-30 14:34
Can you please share the solution

**Comment by poly-eric** [comment] 2020-04-02 04:38
In my view, this problem is caused by your credential is stored in SSL cert with msal.. (you may try to clear ssl cert in internet option) but msal logout does not remove your certification... so when you attempt to the login page, it keeps you sign-in..

**Comment by svr1106** [comment] 2020-09-03 17:33
anyone got the solution ?

**Comment by jasonnutter** [comment] 2021-05-07 21:18
To enable post logout redirect, you need to register a front-channel logout uri, and add your post logout redirect as a redirect uri in your app registration in teh Azure portal.

Closing, if you are still having issues, please open a new issue at the MSAL.js repo (where we are moving ADAL.js): https://github.com/AzureAD/microsoft-authentication-library-for-js/issues

**Closed as completed by jasonnutter** 2021-05-07 21:18 UTC
Labels: Needs Info, Issue Triage
